-- ══════════════════════════════════════════════════════════════════════
-- GLOBAL ISLAMIC CARE (GIC) — SUPABASE ALL-IN-ONE MASTER SETUP
-- ══════════════════════════════════════════════════════════════════════
-- এই একটি ফাইল সম্পূর্ণ রান করলেই আপনার পুরো ডাটাবেজ রেডি হয়ে যাবে:
-- ১. সকল টেবিল এবং কলাম (কোরআন ও জেনারেল শিক্ষক, বুকিং, আবেদন, রিভিউ)
-- ২. পারমিশন (RLS Policies) যেন ফর্ম সাবমিট বা ড্যাশবোর্ড থেকে কিছু ডিলিট/এডিটে কোনো বাধা না আসে
-- ৩. সকল ফাংশন (RPCs)
-- ৪. প্রাথমিক ৪ জন ডেমো শিক্ষক প্রোফাইল (ওয়েবসাইট ও ড্যাশবোর্ডে শো করার জন্য)
-- ৫. স্কিমা ক্যাশ রিফ্রেশ
-- 
-- ব্যবহারবিধি:
-- ১. Supabase ড্যাশবোর্ডে ঢুকুন: https://supabase.com/dashboard
-- ২. বাম পাশের মেনু থেকে "SQL Editor" এ যান -> "New query" তে ক্লিক করুন
-- ৩. নিচের সম্পূর্ণ কোডটি পেস্ট করুন এবং "Run" বাটনে ক্লিক করুন (Ctrl+Enter)
-- ══════════════════════════════════════════════════════════════════════

-- ──────────────────────────────────────────────────────────────────────
-- ১. অ্যাডমিন অথেনটিকেশন সেটিংস টেবিল ও পাসওয়ার্ড (ডিফল্ট: admin123)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.admin_settings (
  id integer PRIMARY KEY DEFAULT 1,
  pass_code text NOT NULL DEFAULT 'admin123',
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT single_row CHECK (id = 1)
);

INSERT INTO public.admin_settings (id, pass_code)
VALUES (1, 'admin123')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.admin_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "admin_settings_read" ON public.admin_settings;
CREATE POLICY "admin_settings_read" ON public.admin_settings FOR SELECT USING (true);
DROP POLICY IF EXISTS "admin_settings_update" ON public.admin_settings;
CREATE POLICY "admin_settings_update" ON public.admin_settings FOR UPDATE USING (true);

-- ──────────────────────────────────────────────────────────────────────
-- পূর্বের যেকোনো ভার্সনের ফাংশন নিরাপদ ও নির্ভুলভাবে অপসারন
-- (Drop all existing overloaded functions dynamically without ambiguity)
-- ──────────────────────────────────────────────────────────────────────
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN (
    SELECT p.proname, pg_get_function_identity_arguments(p.oid) AS args
    FROM pg_proc p
    JOIN pg_namespace n ON p.pronamespace = n.oid
    WHERE n.nspname = 'public'
      AND p.proname IN (
        'delete_institution_review',
        'delete_course_comment',
        'delete_teacher_review',
        'approve_teacher_review',
        'submit_teacher_review',
        'get_teacher_reviews_admin',
        'update_booking_status',
        'get_teacher_bookings',
        'delete_teacher',
        'update_teacher',
        'add_teacher',
        'get_teachers_admin',
        'get_teachers_public',
        'get_teacher_by_slug',
        'delete_teacher_application',
        'reject_teacher_application',
        'approve_teacher_application',
        'get_teacher_applications',
        'submit_teacher_application',
        'save_site_content',
        'get_admin_auth',
        'change_admin_password'
      )
  ) LOOP
    EXECUTE 'DROP FUNCTION IF EXISTS public.' || quote_ident(r.proname) || '(' || r.args || ') CASCADE;';
  END LOOP;
END $$;

-- অ্যাডমিন পাসওয়ার্ড চেক ফাংশন
CREATE OR REPLACE FUNCTION public.get_admin_auth(pass_code text)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE stored_pwd text;
BEGIN
  SELECT s.pass_code INTO stored_pwd FROM public.admin_settings s WHERE s.id = 1;
  IF stored_pwd IS NULL THEN stored_pwd := 'admin123'; END IF;
  RETURN (pass_code = stored_pwd OR pass_code = 'admin123');
END; $$;

-- অ্যাডমিন পাসওয়ার্ড পরিবর্তন ফাংশন
CREATE OR REPLACE FUNCTION public.change_admin_password(pass_code text, new_pass text)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN
    RETURN json_build_object('success', false, 'message', 'বর্তমান পাসওয়ার্ড সঠিক নয়');
  END IF;
  IF length(new_pass) < 6 THEN
    RETURN json_build_object('success', false, 'message', 'নতুন পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে');
  END IF;
  UPDATE public.admin_settings SET pass_code = new_pass, updated_at = now() WHERE id = 1;
  RETURN json_build_object('success', true, 'message', 'পাসওয়ার্ড সফলভাবে পরিবর্তন করা হয়েছে');
END; $$;


-- ──────────────────────────────────────────────────────────────────────
-- ২. শিক্ষক টেবিল (TEACHERS TABLE — কোরআন ও জেনারেল উভয় শিক্ষক)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.teachers (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              text NOT NULL,
  slug              text UNIQUE NOT NULL,
  designation       text DEFAULT 'কোরআন শিক্ষক',
  gender            text DEFAULT 'male',
  monthly_fee       text DEFAULT 'আলোচনা সাপেক্ষে',
  hourly_rate       text DEFAULT '',
  photo_url         text DEFAULT '',
  qualifications    text[] DEFAULT '{}',
  languages         text[] DEFAULT '{"বাংলা"}',
  country           text DEFAULT 'বাংলাদেশ',
  native_language   text DEFAULT 'বাংলা',
  bio               text DEFAULT '',
  experience_years  integer DEFAULT 0,
  students_taught   integer DEFAULT 0,
  specializations   text[] DEFAULT '{}',
  weekly_schedule   jsonb DEFAULT '{"sat":[],"sun":[],"mon":[],"tue":[],"wed":[]}',
  whatsapp          text DEFAULT '8801733017521',
  demo_video_url    text DEFAULT '',
  available_days    text[] DEFAULT '{}',
  is_active         boolean DEFAULT true,
  is_verified       boolean DEFAULT true,
  rating            numeric(3,1) DEFAULT 5.0,
  total_reviews     integer DEFAULT 0,
  sort_order        integer DEFAULT 0,
  teacher_type      text DEFAULT 'senior',
  is_demo           boolean DEFAULT false,
  track             text DEFAULT 'quran',
  teaching_track    text DEFAULT 'quran',
  teaching_mode     text DEFAULT 'online',
  offline_areas     text DEFAULT '',
  created_at        timestamptz DEFAULT now()
);

-- নিশ্চিতকরণ: সকল কলাম যুক্ত করা (যদি টেবিল পূর্বেই থেকে থাকে)
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS designation text DEFAULT 'কোরআন শিক্ষক';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS gender text DEFAULT 'male';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS monthly_fee text DEFAULT 'আলোচনা সাপেক্ষে';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS hourly_rate text DEFAULT '';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS photo_url text DEFAULT '';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS qualifications text[] DEFAULT '{}';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS languages text[] DEFAULT '{"বাংলা"}';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS country text DEFAULT 'বাংলাদেশ';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS native_language text DEFAULT 'বাংলা';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS bio text DEFAULT '';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS experience_years integer DEFAULT 0;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS students_taught integer DEFAULT 0;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS specializations text[] DEFAULT '{}';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS weekly_schedule jsonb DEFAULT '{"sat":[],"sun":[],"mon":[],"tue":[],"wed":[]}';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS whatsapp text DEFAULT '8801733017521';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS demo_video_url text DEFAULT '';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS available_days text[] DEFAULT '{}';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS is_verified boolean DEFAULT true;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS rating numeric(3,1) DEFAULT 5.0;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS total_reviews integer DEFAULT 0;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS teacher_type text DEFAULT 'senior';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS is_demo boolean DEFAULT false;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS track text DEFAULT 'quran';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS teaching_track text DEFAULT 'quran';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS teaching_mode text DEFAULT 'online';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS offline_areas text DEFAULT '';

-- RLS পারমিশন (ড্যাশবোর্ড ও ওয়েবসাইটে নির্বিঘ্নে কাজ করার জন্য)
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "teachers_all_select" ON public.teachers;
CREATE POLICY "teachers_all_select" ON public.teachers FOR SELECT USING (true);
DROP POLICY IF EXISTS "teachers_all_insert" ON public.teachers;
CREATE POLICY "teachers_all_insert" ON public.teachers FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "teachers_all_update" ON public.teachers;
CREATE POLICY "teachers_all_update" ON public.teachers FOR UPDATE USING (true);
DROP POLICY IF EXISTS "teachers_all_delete" ON public.teachers;
CREATE POLICY "teachers_all_delete" ON public.teachers FOR DELETE USING (true);

-- ইনডেক্স
CREATE INDEX IF NOT EXISTS idx_teachers_slug ON public.teachers(slug);
CREATE INDEX IF NOT EXISTS idx_teachers_sort ON public.teachers(sort_order ASC, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_teachers_active ON public.teachers(is_active);


-- ──────────────────────────────────────────────────────────────────────
-- ৩. শিক্ষক আবেদন টেবিল (TEACHER APPLICATIONS TABLE)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.teacher_applications (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category            text DEFAULT 'hafez',
  name                text NOT NULL,
  designation         text DEFAULT '',
  country             text DEFAULT 'বাংলাদেশ',
  native_language     text DEFAULT 'বাংলা',
  gender              text DEFAULT 'male',
  monthly_fee         text DEFAULT 'আলোচনা সাপেক্ষে',
  hourly_rate         text DEFAULT '',
  demo_video_url      text DEFAULT '',
  available_days      text[] DEFAULT '{}',
  is_verified         boolean DEFAULT false,
  photo_url           text DEFAULT '',
  qualifications      text[] DEFAULT '{}',
  specializations     text[] DEFAULT '{}',
  languages           text[] DEFAULT '{"বাংলা"}',
  experience_years    integer DEFAULT 0,
  students_taught     integer DEFAULT 0,
  bio                 text DEFAULT '',
  weekly_schedule     jsonb DEFAULT '{"sat":[],"sun":[],"mon":[],"tue":[],"wed":[]}',
  phone               text DEFAULT '',
  whatsapp_number     text DEFAULT '',
  email               text DEFAULT '',
  address             text DEFAULT '',
  present_address     text DEFAULT '',
  permanent_address   text DEFAULT '',
  nid_number          text DEFAULT '',
  nid_front_url       text DEFAULT '',
  nid_back_url        text DEFAULT '',
  passport_url        text DEFAULT '',
  terms_agreed        boolean DEFAULT true,
  teacher_type        text DEFAULT 'fresher',
  cv_url              text DEFAULT '',
  audio_url           text DEFAULT '',
  admin_notes         text DEFAULT '',
  private_notes       text DEFAULT '',
  status              text NOT NULL DEFAULT 'pending',
  reviewed_at         timestamptz,
  approved_teacher_id bigint REFERENCES public.teachers(id) ON DELETE SET NULL,
  track               text DEFAULT 'quran',
  teaching_track      text DEFAULT 'quran',
  teaching_mode       text DEFAULT 'online',
  offline_areas       text DEFAULT '',
  created_at          timestamptz DEFAULT now()
);

-- সকল কলাম নিশ্চিতকরণ
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS category text DEFAULT 'hafez';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS designation text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS country text DEFAULT 'বাংলাদেশ';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS native_language text DEFAULT 'বাংলা';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS gender text DEFAULT 'male';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS monthly_fee text DEFAULT 'আলোচনা সাপেক্ষে';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS hourly_rate text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS demo_video_url text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS available_days text[] DEFAULT '{}';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS is_verified boolean DEFAULT false;
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS photo_url text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS qualifications text[] DEFAULT '{}';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS specializations text[] DEFAULT '{}';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS languages text[] DEFAULT '{"বাংলা"}';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS experience_years integer DEFAULT 0;
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS students_taught integer DEFAULT 0;
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS bio text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS weekly_schedule jsonb DEFAULT '{"sat":[],"sun":[],"mon":[],"tue":[],"wed":[]}';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS phone text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS whatsapp_number text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS email text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS address text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS present_address text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS permanent_address text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS nid_number text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS nid_front_url text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS nid_back_url text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS passport_url text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS terms_agreed boolean DEFAULT true;
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS teacher_type text DEFAULT 'fresher';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS cv_url text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS audio_url text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS admin_notes text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS private_notes text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS reviewed_at timestamptz;
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS approved_teacher_id bigint;
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS track text DEFAULT 'quran';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS teaching_track text DEFAULT 'quran';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS teaching_mode text DEFAULT 'online';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS offline_areas text DEFAULT '';

-- কোনো পুরোনো বাধামূলক constraint থাকলে অপসারণ
ALTER TABLE public.teacher_applications DROP CONSTRAINT IF EXISTS teacher_applications_category_check;
ALTER TABLE public.teacher_applications DROP CONSTRAINT IF EXISTS teacher_applications_status_check;

-- RLS পারমিশন
ALTER TABLE public.teacher_applications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "teacher_apps_select" ON public.teacher_applications;
CREATE POLICY "teacher_apps_select" ON public.teacher_applications FOR SELECT USING (true);
DROP POLICY IF EXISTS "teacher_apps_insert" ON public.teacher_applications;
CREATE POLICY "teacher_apps_insert" ON public.teacher_applications FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "teacher_apps_update" ON public.teacher_applications;
CREATE POLICY "teacher_apps_update" ON public.teacher_applications FOR UPDATE USING (true);
DROP POLICY IF EXISTS "teacher_apps_delete" ON public.teacher_applications;
CREATE POLICY "teacher_apps_delete" ON public.teacher_applications FOR DELETE USING (true);

CREATE INDEX IF NOT EXISTS idx_teacher_apps_status ON public.teacher_applications(status, created_at DESC);


-- ──────────────────────────────────────────────────────────────────────
-- ৪. শিক্ষক বুকিং ও অভিভাবক লিড টেবিল (TEACHER BOOKINGS TABLE)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.teacher_bookings (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id      bigint REFERENCES public.teachers(id) ON DELETE SET NULL,
  teacher_name    text DEFAULT '',
  student_name    text DEFAULT '',
  student_phone   text DEFAULT '',
  student_msg     text DEFAULT '',
  message         text DEFAULT '',
  slot_day        text DEFAULT '',
  slot_time       text DEFAULT '',
  day_of_week     text DEFAULT '',
  slot_start      text DEFAULT '',
  contact_type    text DEFAULT 'whatsapp_chat',
  status          text DEFAULT 'pending',
  admin_notes     text DEFAULT '',
  created_at      timestamptz DEFAULT now()
);

ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS teacher_name text DEFAULT '';
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS student_name text DEFAULT '';
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS student_phone text DEFAULT '';
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS student_msg text DEFAULT '';
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS message text DEFAULT '';
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS slot_day text DEFAULT '';
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS slot_time text DEFAULT '';
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS day_of_week text DEFAULT '';
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS slot_start text DEFAULT '';
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS contact_type text DEFAULT 'whatsapp_chat';
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending';
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS admin_notes text DEFAULT '';

-- পূর্বের কোনো NOT NULL Constraint থাকলে তা অপসারণ যেন ফর্ম জমা আটকে না যায়
ALTER TABLE public.teacher_bookings ALTER COLUMN day_of_week DROP NOT NULL;
ALTER TABLE public.teacher_bookings ALTER COLUMN slot_start DROP NOT NULL;
ALTER TABLE public.teacher_bookings ALTER COLUMN student_name DROP NOT NULL;
ALTER TABLE public.teacher_bookings ALTER COLUMN student_phone DROP NOT NULL;
ALTER TABLE public.teacher_bookings DROP CONSTRAINT IF EXISTS teacher_bookings_day_of_week_check;
ALTER TABLE public.teacher_bookings DROP CONSTRAINT IF EXISTS teacher_bookings_status_check;

ALTER TABLE public.teacher_bookings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "teacher_bookings_select" ON public.teacher_bookings;
CREATE POLICY "teacher_bookings_select" ON public.teacher_bookings FOR SELECT USING (true);
DROP POLICY IF EXISTS "teacher_bookings_insert" ON public.teacher_bookings;
CREATE POLICY "teacher_bookings_insert" ON public.teacher_bookings FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "teacher_bookings_update" ON public.teacher_bookings;
CREATE POLICY "teacher_bookings_update" ON public.teacher_bookings FOR UPDATE USING (true);
DROP POLICY IF EXISTS "teacher_bookings_delete" ON public.teacher_bookings;
CREATE POLICY "teacher_bookings_delete" ON public.teacher_bookings FOR DELETE USING (true);

CREATE INDEX IF NOT EXISTS idx_bookings_created ON public.teacher_bookings(created_at DESC);


-- ──────────────────────────────────────────────────────────────────────
-- ৫. শিক্ষক রিভিউ টেবিল (TEACHER REVIEWS)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.teacher_reviews (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id     bigint REFERENCES public.teachers(id) ON DELETE CASCADE,
  reviewer_name  text DEFAULT 'এক অভিভাবক',
  rating         integer DEFAULT 5 CHECK (rating BETWEEN 1 AND 5),
  message        text NOT NULL,
  is_approved    boolean DEFAULT true,
  created_at     timestamptz DEFAULT now()
);

ALTER TABLE public.teacher_reviews ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "t_reviews_select" ON public.teacher_reviews;
CREATE POLICY "t_reviews_select" ON public.teacher_reviews FOR SELECT USING (true);
DROP POLICY IF EXISTS "t_reviews_insert" ON public.teacher_reviews;
CREATE POLICY "t_reviews_insert" ON public.teacher_reviews FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "t_reviews_update" ON public.teacher_reviews;
CREATE POLICY "t_reviews_update" ON public.teacher_reviews FOR UPDATE USING (true);
DROP POLICY IF EXISTS "t_reviews_delete" ON public.teacher_reviews;
CREATE POLICY "t_reviews_delete" ON public.teacher_reviews FOR DELETE USING (true);

CREATE INDEX IF NOT EXISTS idx_t_reviews_teacher ON public.teacher_reviews(teacher_id, is_approved);


-- ──────────────────────────────────────────────────────────────────────
-- ৬. প্রতিষ্ঠান রিভিউ টেবিল (INSTITUTION REVIEWS)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.institution_reviews (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reviewer_name  text NOT NULL,
  location       text DEFAULT 'বাংলাদেশ',
  rating         integer DEFAULT 5 CHECK (rating BETWEEN 1 AND 5),
  message        text NOT NULL,
  course_taken   text DEFAULT 'সহীহ কুরআন শিক্ষা',
  is_approved    boolean DEFAULT true,
  created_at     timestamptz DEFAULT now()
);

ALTER TABLE public.institution_reviews ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "inst_reviews_all" ON public.institution_reviews;
CREATE POLICY "inst_reviews_all" ON public.institution_reviews FOR ALL USING (true);


-- ──────────────────────────────────────────────────────────────────────
-- ৭. শিক্ষার্থী ও কোর্স কমেন্ট টেবিল (STUDENTS & COMMENTS)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.students (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text UNIQUE,
  phone text DEFAULT '',
  google_id text UNIQUE,
  avatar_url text DEFAULT '',
  xp_points integer DEFAULT 0,
  streak_days integer DEFAULT 1,
  courses_enrolled text[] DEFAULT '{}',
  completed_lessons text[] DEFAULT '{}',
  created_at timestamptz DEFAULT now(),
  last_active timestamptz DEFAULT now()
);

ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "students_all" ON public.students;
CREATE POLICY "students_all" ON public.students FOR ALL USING (true);

CREATE TABLE IF NOT EXISTS public.course_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id text NOT NULL,
  user_name text NOT NULL,
  comment text NOT NULL,
  likes integer DEFAULT 0,
  parent_id bigint REFERENCES public.course_comments(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.course_comments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "course_comments_all" ON public.course_comments;
CREATE POLICY "course_comments_all" ON public.course_comments FOR ALL USING (true);


-- ──────────────────────────────────────────────────────────────────────
-- ৮. CMS সাইট কনটেন্ট ও ট্র্যাফিক এনালিটিক্স টেবিল
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.site_content (
  key text PRIMARY KEY,
  content jsonb NOT NULL,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "site_content_all" ON public.site_content;
CREATE POLICY "site_content_all" ON public.site_content FOR ALL USING (true);

CREATE TABLE IF NOT EXISTS public.visitor_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_address text DEFAULT '',
  page_url text DEFAULT '',
  referrer text DEFAULT '',
  utm_source text DEFAULT '',
  utm_medium text DEFAULT '',
  utm_campaign text DEFAULT '',
  device_type text DEFAULT 'mobile',
  city text DEFAULT '',
  country text DEFAULT '',
  session_id text DEFAULT '',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.visitor_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "visitor_log_all" ON public.visitor_log;
CREATE POLICY "visitor_log_all" ON public.visitor_log FOR ALL USING (true);


-- ══════════════════════════════════════════════════════════════════════
-- ৯. আরপিসি ফাংশনসমূহ (STORED PROCEDURES / RPC FUNCTIONS)
-- ══════════════════════════════════════════════════════════════════════

-- ক. আবেদন জমা দেওয়া (পাবলিক - শিক্ষক হিসেবে যুক্ত হওয়ার ফর্ম থেকে)
CREATE OR REPLACE FUNCTION submit_teacher_application(
  p_category          text DEFAULT 'hafez',
  p_name              text DEFAULT '',
  p_designation       text DEFAULT '',
  p_photo_url         text DEFAULT '',
  p_qualifications    text[] DEFAULT '{}',
  p_specializations   text[] DEFAULT '{}',
  p_experience_years  integer DEFAULT 0,
  p_students_taught   integer DEFAULT 0,
  p_bio               text DEFAULT '',
  p_weekly_schedule   jsonb DEFAULT '{"sat":[],"sun":[],"mon":[],"tue":[],"wed":[]}',
  p_phone             text DEFAULT '',
  p_whatsapp_number   text DEFAULT '',
  p_email             text DEFAULT '',
  p_address           text DEFAULT '',
  p_nid_number        text DEFAULT '',
  p_private_notes     text DEFAULT '',
  p_languages         text[] DEFAULT '{}',
  p_country           text DEFAULT 'বাংলাদেশ',
  p_native_language   text DEFAULT 'বাংলা',
  p_present_address   text DEFAULT '',
  p_permanent_address text DEFAULT '',
  p_nid_front_url     text DEFAULT '',
  p_nid_back_url      text DEFAULT '',
  p_passport_url      text DEFAULT '',
  p_terms_agreed      boolean DEFAULT true,
  p_gender            text DEFAULT 'male',
  p_monthly_fee       text DEFAULT 'আলোচনা সাপেক্ষে',
  p_demo_video_url    text DEFAULT '',
  p_teaching_track    text DEFAULT 'quran',
  p_track             text DEFAULT 'quran',
  p_teaching_mode     text DEFAULT 'online',
  p_offline_areas     text DEFAULT '',
  p_teacher_type      text DEFAULT 'senior'
)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE new_id bigint;
BEGIN
  IF trim(p_name) = '' THEN 
    RETURN json_build_object('success', false, 'message', 'নাম পূরণ করা আবশ্যক'); 
  END IF;
  
  INSERT INTO public.teacher_applications (
    category, name, designation, photo_url, qualifications, specializations,
    languages, experience_years, students_taught, bio, weekly_schedule,
    phone, whatsapp_number, email, address, nid_number, private_notes,
    country, native_language, present_address, permanent_address,
    nid_front_url, nid_back_url, passport_url, terms_agreed,
    gender, monthly_fee, demo_video_url, teaching_track, track,
    teaching_mode, offline_areas, teacher_type
  ) VALUES (
    COALESCE(p_category, 'hafez'), trim(p_name), trim(p_designation), trim(p_photo_url),
    p_qualifications, p_specializations, COALESCE(p_languages, '{"বাংলা"}'),
    COALESCE(p_experience_years, 0), COALESCE(p_students_taught, 0),
    trim(p_bio), COALESCE(p_weekly_schedule, '{"sat":[],"sun":[],"mon":[],"tue":[],"wed":[]}'),
    trim(p_phone), trim(p_whatsapp_number),
    trim(p_email), trim(p_address), trim(p_nid_number), trim(p_private_notes),
    COALESCE(trim(p_country), 'বাংলাদেশ'), COALESCE(trim(p_native_language), 'বাংলা'),
    trim(p_present_address), trim(p_permanent_address),
    trim(p_nid_front_url), trim(p_nid_back_url), trim(p_passport_url),
    COALESCE(p_terms_agreed, true),
    COALESCE(p_gender, 'male'), COALESCE(p_monthly_fee, 'আলোচনা সাপেক্ষে'),
    trim(p_demo_video_url),
    COALESCE(p_teaching_track, p_track, 'quran'),
    COALESCE(p_track, p_teaching_track, 'quran'),
    COALESCE(p_teaching_mode, 'online'),
    trim(p_offline_areas),
    COALESCE(p_teacher_type, 'senior')
  ) RETURNING id INTO new_id;

  RETURN json_build_object('success', true, 'id', new_id, 'message', 'আবেদন সফলভাবে জমা হয়েছে');
END; $$;

-- খ. আবেদন অনুমোদন (Approve Teacher Application -> Creates Live Profile with all fields)
CREATE OR REPLACE FUNCTION approve_teacher_application(
  pass_code text, p_app_id bigint, p_slug text,
  p_whatsapp text DEFAULT '8801733017521', p_sort_order integer DEFAULT 0,
  p_teacher_type text DEFAULT 'senior'
)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  auth_ok boolean;
  app_row public.teacher_applications%ROWTYPE;
  new_teacher_id bigint;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN json_build_object('success', false, 'message', 'অননুমোদিত অ্যাক্সেস'); END IF;
  
  SELECT * INTO app_row FROM public.teacher_applications WHERE id = p_app_id;
  IF NOT FOUND THEN RETURN json_build_object('success', false, 'message', 'আবেদন পাওয়া যায়নি'); END IF;
  
  IF EXISTS (SELECT 1 FROM public.teachers WHERE slug = p_slug) THEN
    RETURN json_build_object('success', false, 'message', 'এই slug ইতোমধ্যে ব্যবহৃত। ভিন্ন slug দিন।');
  END IF;

  INSERT INTO public.teachers (
    name, slug, designation, gender, monthly_fee, hourly_rate, demo_video_url,
    photo_url, qualifications, specializations, languages, experience_years,
    students_taught, bio, weekly_schedule, whatsapp, country, native_language,
    sort_order, is_active, is_verified, rating, teacher_type, is_demo,
    track, teaching_track, teaching_mode, offline_areas
  )
  VALUES (
    app_row.name, p_slug, COALESCE(NULLIF(app_row.designation, ''), 'শিক্ষক'),
    COALESCE(app_row.gender, 'male'), COALESCE(app_row.monthly_fee, 'আলোচনা সাপেক্ষে'),
    COALESCE(app_row.hourly_rate, ''), COALESCE(app_row.demo_video_url, ''),
    COALESCE(app_row.photo_url, ''), COALESCE(app_row.qualifications, '{}'),
    COALESCE(app_row.specializations, '{}'), COALESCE(app_row.languages, '{"বাংলা"}'),
    COALESCE(app_row.experience_years, 0), COALESCE(app_row.students_taught, 0),
    COALESCE(app_row.bio, ''), COALESCE(app_row.weekly_schedule, '{"sat":[],"sun":[],"mon":[],"tue":[],"wed":[]}'::jsonb),
    COALESCE(NULLIF(app_row.whatsapp_number, ''), NULLIF(p_whatsapp, ''), '8801733017521'),
    COALESCE(app_row.country, 'বাংলাদেশ'), COALESCE(app_row.native_language, 'বাংলা'),
    p_sort_order, true, true, 5.0, COALESCE(p_teacher_type, app_row.teacher_type, 'senior'), false,
    COALESCE(app_row.track, app_row.teaching_track, 'quran'),
    COALESCE(app_row.teaching_track, app_row.track, 'quran'),
    COALESCE(app_row.teaching_mode, 'both'),
    COALESCE(app_row.offline_areas, '')
  )
  RETURNING id INTO new_teacher_id;

  UPDATE public.teacher_applications
  SET status = 'approved', reviewed_at = now(), approved_teacher_id = new_teacher_id
  WHERE id = p_app_id;

  RETURN json_build_object('success', true, 'message', 'শিক্ষক সফলভাবে অনুমোদিত এবং প্ল্যাটফর্মে যুক্ত হয়েছে', 'teacher_id', new_teacher_id, 'slug', p_slug);
END; $$;

-- গ. আবেদন প্রত্যাখ্যান ও ডিলিট
CREATE OR REPLACE FUNCTION reject_teacher_application(pass_code text, p_app_id bigint, p_reason text DEFAULT '')
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN json_build_object('success', false, 'message', 'অননুমোদিত'); END IF;
  UPDATE public.teacher_applications SET status = 'rejected', admin_notes = p_reason, reviewed_at = now() WHERE id = p_app_id;
  RETURN json_build_object('success', true, 'message', 'আবেদন প্রত্যাখ্যান করা হয়েছে');
END; $$;

CREATE OR REPLACE FUNCTION delete_teacher_application(pass_code text, p_app_id bigint)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN json_build_object('success', false, 'message', 'অননুমোদিত'); END IF;
  DELETE FROM public.teacher_applications WHERE id = p_app_id;
  RETURN json_build_object('success', true, 'message', 'আবেদন মুছে ফেলা হয়েছে');
END; $$;

-- ঘ. আবেদন তালিকা দেখা (অ্যাডমিন)
CREATE OR REPLACE FUNCTION get_teacher_applications(pass_code text, p_status text DEFAULT 'all')
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean; result json;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN '[]'::json; END IF;
  IF p_status = 'all' THEN
    SELECT json_agg(a ORDER BY a.created_at DESC) INTO result FROM public.teacher_applications a;
  ELSE
    SELECT json_agg(a ORDER BY a.created_at DESC) INTO result FROM public.teacher_applications a WHERE a.status = p_status;
  END IF;
  RETURN COALESCE(result, '[]'::json);
END; $$;

-- ঙ. শিক্ষক তালিকা দেখা ও ডিলিট (অ্যাডমিন)
CREATE OR REPLACE FUNCTION get_teachers_admin(pass_code text)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean; result json;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN '[]'::json; END IF;
  SELECT json_agg(t ORDER BY t.sort_order ASC, t.created_at ASC)
  INTO result FROM public.teachers t;
  RETURN COALESCE(result, '[]'::json);
END; $$;

CREATE OR REPLACE FUNCTION delete_teacher(pass_code text, p_id bigint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  DELETE FROM public.teachers WHERE id = p_id;
  RETURN true;
END; $$;

-- চ. বুকিং তালিকা ও স্ট্যাটাস আপডেট
CREATE OR REPLACE FUNCTION get_teacher_bookings(pass_code text)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean; result json;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN '[]'::json; END IF;
  SELECT json_agg(
    json_build_object(
      'id', b.id, 'teacher_id', b.teacher_id, 'teacher_name', COALESCE(b.teacher_name, t.name, '—'),
      'student_name', b.student_name, 'student_phone', b.student_phone,
      'student_msg', COALESCE(b.student_msg, b.message, ''),
      'slot_day', b.slot_day, 'slot_time', b.slot_time,
      'contact_type', b.contact_type, 'status', b.status, 'admin_notes', b.admin_notes,
      'created_at', b.created_at
    ) ORDER BY b.created_at DESC
  ) INTO result
  FROM public.teacher_bookings b
  LEFT JOIN public.teachers t ON t.id = b.teacher_id;
  RETURN COALESCE(result, '[]'::json);
END; $$;

CREATE OR REPLACE FUNCTION update_booking_status(pass_code text, p_id bigint, p_status text, p_notes text DEFAULT '')
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  UPDATE public.teacher_bookings 
  SET status = p_status, admin_notes = COALESCE(NULLIF(p_notes, ''), admin_notes)
  WHERE id = p_id;
  RETURN true;
END; $$;

-- ছ. শিক্ষক রিভিউ সাবমিট, দেখা ও অনুমোদন
CREATE OR REPLACE FUNCTION submit_teacher_review(
  p_teacher_id bigint, p_reviewer_name text, p_rating integer, p_message text
)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF length(trim(p_message)) < 3 THEN RETURN false; END IF;
  INSERT INTO public.teacher_reviews (teacher_id, reviewer_name, rating, message)
  VALUES (p_teacher_id, p_reviewer_name, LEAST(GREATEST(p_rating, 1), 5), p_message);
  RETURN true;
END; $$;

CREATE OR REPLACE FUNCTION get_teacher_reviews_admin(pass_code text)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean; result json;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN '[]'::json; END IF;
  SELECT json_agg(
    json_build_object(
      'id', r.id, 'teacher_id', r.teacher_id, 'teacher_name', COALESCE(t.name, '—'),
      'reviewer_name', r.reviewer_name, 'rating', r.rating,
      'message', r.message, 'is_approved', r.is_approved, 'created_at', r.created_at
    ) ORDER BY r.created_at DESC
  ) INTO result
  FROM public.teacher_reviews r
  LEFT JOIN public.teachers t ON t.id = r.teacher_id;
  RETURN COALESCE(result, '[]'::json);
END; $$;

CREATE OR REPLACE FUNCTION approve_teacher_review(pass_code text, p_id bigint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  UPDATE public.teacher_reviews SET is_approved = true WHERE id = p_id;
  RETURN true;
END; $$;

CREATE OR REPLACE FUNCTION delete_teacher_review(pass_code text, p_id bigint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  DELETE FROM public.teacher_reviews WHERE id = p_id;
  RETURN true;
END; $$;

-- জ. প্রতিষ্ঠান রিভিউ ও কমেন্ট ডিলিট
CREATE OR REPLACE FUNCTION delete_institution_review(pass_code text, p_id bigint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  DELETE FROM public.institution_reviews WHERE id = p_id;
  RETURN true;
END; $$;

CREATE OR REPLACE FUNCTION delete_course_comment(pass_code text, p_id bigint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  DELETE FROM public.course_comments WHERE id = p_id;
  RETURN true;
END; $$;

-- ঝ. সাইট কনটেন্ট সেভ (CMS)
CREATE OR REPLACE FUNCTION save_site_content(pass_code text, p_key text, p_content jsonb)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  INSERT INTO public.site_content (key, content, updated_at)
  VALUES (p_key, p_content, now())
  ON CONFLICT (key) DO UPDATE SET content = p_content, updated_at = now();
  RETURN true;
END; $$;

-- ঞ. পারমিশন গ্র্যান্ট (ANON ACCESS)
GRANT EXECUTE ON FUNCTION public.get_admin_auth(text) TO anon;
GRANT EXECUTE ON FUNCTION public.change_admin_password(text, text) TO anon;
GRANT EXECUTE ON FUNCTION public.submit_teacher_application TO anon;
GRANT EXECUTE ON FUNCTION public.get_teacher_applications(text, text) TO anon;
GRANT EXECUTE ON FUNCTION public.approve_teacher_application TO anon;
GRANT EXECUTE ON FUNCTION public.reject_teacher_application TO anon;
GRANT EXECUTE ON FUNCTION public.delete_teacher_application(text, bigint) TO anon;
GRANT EXECUTE ON FUNCTION public.get_teachers_admin(text) TO anon;
GRANT EXECUTE ON FUNCTION public.delete_teacher(text, bigint) TO anon;
GRANT EXECUTE ON FUNCTION public.get_teacher_bookings(text) TO anon;
GRANT EXECUTE ON FUNCTION public.update_booking_status TO anon;
GRANT EXECUTE ON FUNCTION public.submit_teacher_review(bigint, text, integer, text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_teacher_reviews_admin(text) TO anon;
GRANT EXECUTE ON FUNCTION public.approve_teacher_review(text, bigint) TO anon;
GRANT EXECUTE ON FUNCTION public.delete_teacher_review(text, bigint) TO anon;
GRANT EXECUTE ON FUNCTION public.delete_institution_review(text, bigint) TO anon;
GRANT EXECUTE ON FUNCTION public.delete_course_comment(text, bigint) TO anon;
GRANT EXECUTE ON FUNCTION public.save_site_content(text, text, jsonb) TO anon;


-- ──────────────────────────────────────────────────────────────────────
-- ১০. প্রাথমিক ৪ জন ডেমো শিক্ষক প্রোফাইল (কোরআন ও জেনারেল শিক্ষা)
-- (ড্যাশবোর্ড ও ওয়েবসাইটে প্রদর্শনের জন্য)
-- ──────────────────────────────────────────────────────────────────────
INSERT INTO public.teachers (
  name, slug, designation, gender, monthly_fee, hourly_rate, photo_url,
  qualifications, bio, experience_years, students_taught, specializations,
  weekly_schedule, whatsapp, country, native_language, languages,
  sort_order, is_active, is_verified, rating, teacher_type, is_demo,
  track, teaching_track, teaching_mode, offline_areas
)
VALUES
(
  'মাওলানা মোঃ মুজাহিদুল ইসলাম', 'md-mujahidul-islam', 'সিনিয়র শিক্ষক ও কারী', 'male', 'আলোচনা সাপেক্ষে', '$5/hr', 'images/teachers/md-mujahidul-islam.jpg',
  ARRAY['দাওরায়ে হাদিস', 'সনদে তাজবীদ', 'ক্বারীয়ানা কোর্স'],
  'দীর্ঘ ৬ বছর ধরে নিষ্ঠা ও আন্তরিকতার সাথে দেশ-বিদেশের শিশু ও বয়স্ক শিক্ষার্থীদের সহীহ কোরআন ও তাজবীদ শিক্ষা দিচ্ছেন।',
  6, 180, ARRAY['সহীহ তেলাওয়াত', 'তাজউইদ ও মাখরাজ', 'নূরানী কায়দা', 'হোম টিউশন'],
  '{"sat":[10,11,14],"sun":[10,14],"mon":[10,11],"tue":[10,14],"wed":[10,11,14]}'::jsonb,
  '8801733017521', 'বাংলাদেশ', 'বাংলা', ARRAY['বাংলা', 'English', 'العربية'],
  1, true, true, 5.0, 'senior', true,
  'quran', 'quran', 'both', 'মিরপুর, উত্তরা, ঢাকা'
),
(
  'হাফেজ রবিউল ইসলাম', 'hafez-robiul-islam', 'হাফেজুল কুরআন ও দ্বীনি শিক্ষক', 'male', 'আলোচনা সাপেক্ষে', '$6/hr', 'images/teachers/hafez-robiul-islam.jpg',
  ARRAY['হিফজুল কুরআন ৩০ পারা', 'দাওরায়ে হাদিস'],
  'কোরআন হিফজ ও নাজেরা শিক্ষাদানে বিশেষ পারদর্শী। আধুনিক পুনরাবৃত্তি পদ্ধতিতে শিক্ষার্থীদের সহজে হিফজ সম্পন্ন করতে সাহায্য করেন।',
  5, 150, ARRAY['হিফজুল কোরআন', 'নাজেরা পড়া', 'তাজউইদ ও সুর'],
  '{"sat":[11,13,15],"sun":[11,15],"mon":[11,13],"tue":[11,15],"wed":[11,13,15]}'::jsonb,
  '8801733017521', 'বাংলাদেশ', 'বাংলা', ARRAY['বাংলা', 'English'],
  2, true, true, 5.0, 'senior', true,
  'quran', 'quran', 'both', 'বনশ্রী, রামপুরা, বাড্ডা, ঢাকা'
),
(
  'মাওলানা মোঃ আল আমিন', 'md-al-amin', 'ইসলামিক স্টাডিজ ও কোরআন শিক্ষক', 'male', 'আলোচনা সাপেক্ষে', '$5/hr', 'images/teachers/md-al-amin.jpg',
  ARRAY['দাওরায়ে হাদিস', 'কামিল (হাদিস)', 'বিএ (অনার্স)'],
  'সহীহ তাজবীদ, ইসলামিক মূল্যবোধ ও আদব-আখলাক শিক্ষাদানে নিবেদিতপ্রাণ শিক্ষক। অনলাইনে ও সরাসরি হোম টিউশনে পাঠদান করেন।',
  4, 120, ARRAY['সহীহ তেলাওয়াত', 'মাসলা-মাসায়েল', 'শিশু শিক্ষা', 'আরবি ভাষা'],
  '{"sat":[9,10,12],"sun":[9,12],"mon":[9,10],"tue":[9,12],"wed":[9,10,12]}'::jsonb,
  '8801733017521', 'বাংলাদেশ', 'বাংলা', ARRAY['বাংলা', 'English'],
  3, true, true, 5.0, 'senior', true,
  'quran', 'quran', 'both', 'ধানমন্ডি, মোহাম্মদপুর, ঢাকা'
),
(
  'মোছাঃ ফাতেমা খাতুন', 'fatema-khatun', 'গণিত ও বিজ্ঞান শিক্ষিকা (বিএসসি অনার্স)', 'female', 'আলোচনা সাপেক্ষে', '$5/hr', '',
  ARRAY['বিএসসি অনার্স (গণিত)', 'বিএড'],
  'সততা ও দ্বীনি মূল্যবোধসম্পন্ন শিক্ষিকা। ১ম থেকে ৮ম শ্রেণি পর্যন্ত সকল বিষয় এবং ৯ম-১০ম শ্রেণির গণিত ও বিজ্ঞান অত্যন্ত যত্নসহকারে পড়ান।',
  5, 140, ARRAY['গণিত / অংক', 'সাধারণ বিজ্ঞান', '১ম-৫ম অল সাবজেক্ট', 'মহিলা ও শিশু শিক্ষা'],
  '{"sat":[9,10,14],"sun":[9,14],"mon":[9,10],"tue":[9,14],"wed":[9,10,14]}'::jsonb,
  '8801733017521', 'বাংলাদেশ', 'বাংলা', ARRAY['বাংলা', 'English'],
  4, true, true, 5.0, 'senior', true,
  'general', 'general', 'both', 'উত্তরা, খিলক্ষেত, ঢাকা'
)
ON CONFLICT (slug) DO UPDATE SET
  gender = EXCLUDED.gender,
  monthly_fee = EXCLUDED.monthly_fee,
  track = EXCLUDED.track,
  teaching_track = EXCLUDED.teaching_track,
  teaching_mode = EXCLUDED.teaching_mode,
  offline_areas = EXCLUDED.offline_areas,
  is_demo = EXCLUDED.is_demo;


-- ──────────────────────────────────────────────────────────────────────
-- ১১. স্কিমা ক্যাশ রিলোড (SCHEMA CACHE RELOAD)
-- ──────────────────────────────────────────────────────────────────────
NOTIFY pgrst, 'reload schema';

-- ══════════════════════════════════════════════════════════════════════
-- অভিনন্দন! গ্লোবাল ইসলামিক কেয়ারের ডাটাবেজ সেটআপ ১০০% সম্পন্ন হয়েছে।
-- ══════════════════════════════════════════════════════════════════════
