-- ══════════════════════════════════════════════════════════════
-- GIC TEACHER APPLICATION SYSTEM — Database Migration
-- Run this in Supabase SQL Editor
-- ══════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────
-- TABLE: teacher_applications
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.teacher_applications (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category            text DEFAULT 'hafez',
  name                text NOT NULL,
  designation         text DEFAULT '',
  photo_url           text DEFAULT '',
  qualifications      text[] DEFAULT '{}',
  specializations     text[] DEFAULT '{}',
  languages           text[] DEFAULT '{}',
  experience_years    integer DEFAULT 0,
  students_taught     integer DEFAULT 0,
  bio                 text DEFAULT '',
  weekly_schedule     jsonb DEFAULT '{"sat":[],"sun":[],"mon":[],"tue":[],"wed":[]}',
  phone               text DEFAULT '',
  whatsapp_number     text DEFAULT '',
  email               text DEFAULT '',
  address             text DEFAULT '',
  nid_number          text DEFAULT '',
  private_notes       text DEFAULT '',
  status              text NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending', 'approved', 'rejected')),
  reviewed_at         timestamptz,
  approved_teacher_id bigint REFERENCES public.teachers(id) ON DELETE SET NULL,
  created_at          timestamptz DEFAULT now()
);

-- Ensure columns exist if table was already created
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS languages text[] DEFAULT '{}';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS country text DEFAULT 'বাংলাদেশ';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS native_language text DEFAULT 'বাংলা';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS present_address text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS permanent_address text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS nid_front_url text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS nid_back_url text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS passport_url text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS terms_agreed boolean DEFAULT true;
ALTER TABLE public.teacher_applications DROP CONSTRAINT IF EXISTS teacher_applications_category_check;

ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS languages text[] DEFAULT '{}';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS country text DEFAULT 'বাংলাদেশ';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS native_language text DEFAULT 'বাংলা';

ALTER TABLE public.teacher_applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "app_public_insert" ON public.teacher_applications;
CREATE POLICY "app_public_insert" ON public.teacher_applications FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "app_no_public_read" ON public.teacher_applications;
CREATE POLICY "app_no_public_read" ON public.teacher_applications FOR SELECT USING (false);

CREATE INDEX IF NOT EXISTS idx_teacher_apps_status ON public.teacher_applications(status, created_at DESC);

-- 1. PUBLIC: Submit teacher application
CREATE OR REPLACE FUNCTION submit_teacher_application(
  p_category          text DEFAULT 'hafez',
  p_name              text DEFAULT '',
  p_designation       text DEFAULT '',
  p_photo_url         text DEFAULT '',
  p_qualifications    text[] DEFAULT '{}',
  p_specializations   text[] DEFAULT '{}',
  p_experience_years  integer DEFAULT 0,
  p_students_taught   integer DEFAULT 0,
  p_bio               text DEFAULT '',
  p_weekly_schedule   jsonb DEFAULT '{"sat":[],"sun":[],"mon":[],"tue":[],"wed":[]}',
  p_phone             text DEFAULT '',
  p_whatsapp_number   text DEFAULT '',
  p_email             text DEFAULT '',
  p_address           text DEFAULT '',
  p_nid_number        text DEFAULT '',
  p_private_notes     text DEFAULT '',
  p_languages         text[] DEFAULT '{}',
  p_country           text DEFAULT 'বাংলাদেশ',
  p_native_language   text DEFAULT 'বাংলা',
  p_present_address   text DEFAULT '',
  p_permanent_address text DEFAULT '',
  p_nid_front_url     text DEFAULT '',
  p_nid_back_url      text DEFAULT '',
  p_passport_url      text DEFAULT '',
  p_terms_agreed      boolean DEFAULT true
)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE new_id bigint;
BEGIN
  IF trim(p_name) = '' THEN 
    RETURN json_build_object('success', false, 'message', 'নাম পূরণ করা আবশ্যক'); 
  END IF;
  
  IF trim(p_phone) = '' THEN
    RETURN json_build_object('success', false, 'message', 'ব্যক্তিগত ফোন নম্বর আবশ্যক');
  END IF;

  IF trim(p_whatsapp_number) = '' THEN
    RETURN json_build_object('success', false, 'message', 'WhatsApp নম্বর আবশ্যক');
  END IF;

  INSERT INTO public.teacher_applications (
    category, name, designation, photo_url, qualifications, specializations,
    languages, experience_years, students_taught, bio, weekly_schedule,
    phone, whatsapp_number, email, address, nid_number, private_notes,
    country, native_language, present_address, permanent_address,
    nid_front_url, nid_back_url, passport_url, terms_agreed
  ) VALUES (
    COALESCE(p_category, 'hafez'), trim(p_name), trim(p_designation), trim(p_photo_url),
    p_qualifications, p_specializations, COALESCE(p_languages, '{}'),
    COALESCE(p_experience_years, 0), COALESCE(p_students_taught, 0),
    trim(p_bio), COALESCE(p_weekly_schedule, '{"sat":[],"sun":[],"mon":[],"tue":[],"wed":[]}'),
    trim(p_phone), trim(p_whatsapp_number),
    trim(p_email), trim(p_address), trim(p_nid_number), trim(p_private_notes),
    COALESCE(trim(p_country), 'বাংলাদেশ'), COALESCE(trim(p_native_language), 'বাংলা'),
    trim(p_present_address), trim(p_permanent_address),
    trim(p_nid_front_url), trim(p_nid_back_url), trim(p_passport_url),
    COALESCE(p_terms_agreed, true)
  ) RETURNING id INTO new_id;

  RETURN json_build_object('success', true, 'id', new_id, 'message', 'আবেদন সফলভাবে জমা হয়েছে');
END; $$;

-- 2. ADMIN: Get all applications
CREATE OR REPLACE FUNCTION get_teacher_applications(pass_code text, p_status text DEFAULT 'all')
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean; result json;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN '[]'::json; END IF;
  
  IF p_status = 'all' THEN
    SELECT json_agg(a ORDER BY a.created_at DESC) INTO result FROM public.teacher_applications a;
  ELSE
    SELECT json_agg(a ORDER BY a.created_at DESC) INTO result
    FROM public.teacher_applications a WHERE a.status = p_status;
  END IF;
  
  RETURN COALESCE(result, '[]'::json);
END; $$;

-- 3. ADMIN: Approve application → create teacher
CREATE OR REPLACE FUNCTION approve_teacher_application(
  pass_code text, p_app_id bigint, p_slug text,
  p_whatsapp text DEFAULT '8801733017521', p_sort_order integer DEFAULT 0
)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  auth_ok boolean;
  app_row public.teacher_applications%ROWTYPE;
  new_teacher_id bigint;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN json_build_object('success', false, 'message', 'Unauthorized'); END IF;
  
  SELECT * INTO app_row FROM public.teacher_applications WHERE id = p_app_id;
  IF NOT FOUND THEN RETURN json_build_object('success', false, 'message', 'আবেদন পাওয়া যায়নি'); END IF;
  
  IF EXISTS (SELECT 1 FROM public.teachers WHERE slug = p_slug) THEN
    RETURN json_build_object('success', false, 'message', 'এই slug ইতোমধ্যে ব্যবহৃত। ভিন্ন slug দিন।');
  END IF;

  INSERT INTO public.teachers (
    name, slug, photo_url, designation, qualifications, bio,
    experience_years, students_taught, specializations, languages,
    weekly_schedule, whatsapp, is_active, sort_order, country, native_language
  ) VALUES (
    app_row.name, p_slug, app_row.photo_url, app_row.designation,
    app_row.qualifications, app_row.bio, app_row.experience_years,
    app_row.students_taught, app_row.specializations, COALESCE(app_row.languages, '{}'),
    app_row.weekly_schedule,
    CASE WHEN trim(app_row.whatsapp_number) <> '' THEN app_row.whatsapp_number ELSE p_whatsapp END,
    true, p_sort_order,
    COALESCE(app_row.country, 'বাংলাদেশ'), COALESCE(app_row.native_language, 'বাংলা')
  ) RETURNING id INTO new_teacher_id;

  UPDATE public.teacher_applications
  SET status = 'approved', reviewed_at = now(), approved_teacher_id = new_teacher_id
  WHERE id = p_app_id;

  RETURN json_build_object('success', true, 'teacher_id', new_teacher_id, 'message', 'আবেদন অনুমোদিত এবং শিক্ষক প্রোফাইল তৈরি হয়েছে');
END; $$;

-- 4. ADMIN: Reject application
CREATE OR REPLACE FUNCTION reject_teacher_application(pass_code text, p_app_id bigint)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN json_build_object('success', false, 'message', 'Unauthorized'); END IF;
  
  UPDATE public.teacher_applications SET status = 'rejected', reviewed_at = now() WHERE id = p_app_id;
  RETURN json_build_object('success', true, 'message', 'আবেদন প্রত্যাখ্যান করা হয়েছে');
END; $$;

-- 5. ADMIN: Delete application
CREATE OR REPLACE FUNCTION delete_teacher_application(pass_code text, p_app_id bigint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  DELETE FROM public.teacher_applications WHERE id = p_app_id;
  RETURN true;
END; $$;

GRANT EXECUTE ON FUNCTION submit_teacher_application(text,text,text,text,text[],text[],integer,integer,text,jsonb,text,text,text,text,text,text,text[],text,text,text,text,text,text,text,boolean) TO anon;
GRANT EXECUTE ON FUNCTION get_teacher_applications(text,text) TO anon;
GRANT EXECUTE ON FUNCTION approve_teacher_application(text,bigint,text,text,integer) TO anon;
GRANT EXECUTE ON FUNCTION reject_teacher_application(text,bigint) TO anon;
GRANT EXECUTE ON FUNCTION delete_teacher_application(text,bigint) TO anon;
