-- ══════════════════════════════════════════════════════════════
-- GIC TEACHER MANAGEMENT SYSTEM — Database Setup
-- Run this in Supabase SQL Editor
-- ══════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────
-- TABLE 1: teachers
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.teachers (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              text NOT NULL,
  slug              text UNIQUE NOT NULL,
  photo_url         text DEFAULT '',
  designation       text DEFAULT '',
  qualifications    text[] DEFAULT '{}',
  languages         text[] DEFAULT '{"বাংলা"}',
  country           text DEFAULT 'বাংলাদেশ',
  native_language   text DEFAULT 'বাংলা',
  bio               text DEFAULT '',
  experience_years  integer DEFAULT 0,
  students_taught   integer DEFAULT 0,
  specializations   text[] DEFAULT '{}',
  weekly_schedule   jsonb DEFAULT '{"sat":[],"sun":[],"mon":[],"tue":[],"wed":[]}',
  whatsapp          text DEFAULT '8801733017521',
  is_active         boolean DEFAULT true,
  sort_order        integer DEFAULT 0,
  created_at        timestamptz DEFAULT now()
);

ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS languages text[] DEFAULT '{"বাংলা"}';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS country text DEFAULT 'বাংলাদেশ';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS native_language text DEFAULT 'বাংলা';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS teacher_type text DEFAULT 'senior';

ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "teachers_public_read" ON public.teachers FOR SELECT USING (true);
CREATE POLICY "teachers_no_public_write" ON public.teachers FOR INSERT WITH CHECK (false);
CREATE POLICY "teachers_no_public_update" ON public.teachers FOR UPDATE USING (false);
CREATE POLICY "teachers_no_public_delete" ON public.teachers FOR DELETE USING (false);

CREATE INDEX IF NOT EXISTS idx_teachers_slug ON public.teachers(slug);
CREATE INDEX IF NOT EXISTS idx_teachers_active ON public.teachers(is_active, sort_order);

-- ─────────────────────────────────────────────
-- TABLE 2: teacher_bookings
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.teacher_bookings (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id      bigint REFERENCES public.teachers(id) ON DELETE CASCADE,
  day_of_week     text NOT NULL CHECK (day_of_week IN ('sat','sun','mon','tue','wed')),
  slot_start      text NOT NULL,
  student_name    text DEFAULT '',
  student_phone   text DEFAULT '',
  message         text DEFAULT '',
  status          text DEFAULT 'pending' CHECK (status IN ('pending','confirmed','cancelled')),
  created_at      timestamptz DEFAULT now()
);

ALTER TABLE public.teacher_bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "bookings_public_insert" ON public.teacher_bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "bookings_no_public_read" ON public.teacher_bookings FOR SELECT USING (false);

CREATE INDEX IF NOT EXISTS idx_bookings_teacher ON public.teacher_bookings(teacher_id, status);

-- ─────────────────────────────────────────────
-- TABLE 3: teacher_reviews
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.teacher_reviews (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id     bigint REFERENCES public.teachers(id) ON DELETE CASCADE,
  reviewer_name  text DEFAULT 'এক অভিভাবক',
  rating         integer DEFAULT 5 CHECK (rating BETWEEN 1 AND 5),
  message        text NOT NULL,
  is_approved    boolean DEFAULT false,
  created_at     timestamptz DEFAULT now()
);

ALTER TABLE public.teacher_reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "t_reviews_public_insert" ON public.teacher_reviews FOR INSERT WITH CHECK (true);
CREATE POLICY "t_reviews_public_read" ON public.teacher_reviews FOR SELECT USING (true);

CREATE INDEX IF NOT EXISTS idx_t_reviews_teacher ON public.teacher_reviews(teacher_id, is_approved);


-- ══════════════════════════════════════════════════════════════
-- RPC FUNCTIONS
-- ══════════════════════════════════════════════════════════════

-- 1. GET ALL ACTIVE TEACHERS (PUBLIC)
CREATE OR REPLACE FUNCTION get_teachers_public()
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE result json;
BEGIN
  SELECT json_agg(t ORDER BY t.sort_order ASC, t.created_at ASC)
  INTO result FROM public.teachers t WHERE t.is_active = true;
  RETURN COALESCE(result, '[]'::json);
END; $$;

-- 2. GET SINGLE TEACHER BY SLUG (PUBLIC)
CREATE OR REPLACE FUNCTION get_teacher_by_slug(p_slug text)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  teacher_row  json;
  reviews_json json;
  result       json;
BEGIN
  SELECT row_to_json(t) INTO teacher_row
  FROM public.teachers t WHERE t.slug = p_slug AND t.is_active = true;
  IF teacher_row IS NULL THEN RETURN NULL; END IF;
  SELECT json_agg(r ORDER BY r.created_at DESC) INTO reviews_json
  FROM public.teacher_reviews r
  WHERE r.teacher_id = (teacher_row->>'id')::bigint AND r.is_approved = true;
  SELECT json_build_object('teacher', teacher_row, 'reviews', COALESCE(reviews_json, '[]'::json)) INTO result;
  RETURN result;
END; $$;

-- 3. ADD TEACHER (ADMIN)
CREATE OR REPLACE FUNCTION add_teacher(
  pass_code text, p_name text, p_slug text,
  p_photo_url text DEFAULT '', p_designation text DEFAULT '',
  p_qualifications text[] DEFAULT '{}', p_bio text DEFAULT '',
  p_experience integer DEFAULT 0, p_students integer DEFAULT 0,
  p_specializations text[] DEFAULT '{}',
  p_schedule jsonb DEFAULT '{"sat":[],"sun":[],"mon":[],"tue":[],"wed":[]}',
  p_whatsapp text DEFAULT '8801733017521', p_sort_order integer DEFAULT 0
)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean; new_id bigint;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN json_build_object('success', false, 'message', 'Unauthorized'); END IF;
  INSERT INTO public.teachers (name, slug, photo_url, designation, qualifications, bio,
    experience_years, students_taught, specializations, weekly_schedule, whatsapp, sort_order)
  VALUES (p_name, p_slug, p_photo_url, p_designation, p_qualifications, p_bio,
    p_experience, p_students, p_specializations, p_schedule, p_whatsapp, p_sort_order)
  RETURNING id INTO new_id;
  RETURN json_build_object('success', true, 'id', new_id, 'message', 'শিক্ষক যোগ করা হয়েছে');
END; $$;

-- 4. UPDATE TEACHER (ADMIN)
CREATE OR REPLACE FUNCTION update_teacher(
  pass_code text, p_id bigint, p_name text, p_slug text,
  p_photo_url text DEFAULT '', p_designation text DEFAULT '',
  p_qualifications text[] DEFAULT '{}', p_bio text DEFAULT '',
  p_experience integer DEFAULT 0, p_students integer DEFAULT 0,
  p_specializations text[] DEFAULT '{}',
  p_schedule jsonb DEFAULT '{"sat":[],"sun":[],"mon":[],"tue":[],"wed":[]}',
  p_whatsapp text DEFAULT '8801733017521', p_sort_order integer DEFAULT 0,
  p_is_active boolean DEFAULT true
)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN json_build_object('success', false, 'message', 'Unauthorized'); END IF;
  UPDATE public.teachers SET
    name = p_name, slug = p_slug, photo_url = p_photo_url, designation = p_designation,
    qualifications = p_qualifications, bio = p_bio, experience_years = p_experience,
    students_taught = p_students, specializations = p_specializations,
    weekly_schedule = p_schedule, whatsapp = p_whatsapp,
    sort_order = p_sort_order, is_active = p_is_active
  WHERE id = p_id;
  RETURN json_build_object('success', true, 'message', 'শিক্ষকের তথ্য আপডেট হয়েছে');
END; $$;

-- 5. DELETE TEACHER (ADMIN)
CREATE OR REPLACE FUNCTION delete_teacher(pass_code text, p_id bigint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  DELETE FROM public.teachers WHERE id = p_id;
  RETURN true;
END; $$;

-- 6. GET ALL TEACHERS ADMIN (includes inactive)
CREATE OR REPLACE FUNCTION get_teachers_admin(pass_code text)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean; result json;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN '[]'::json; END IF;
  SELECT json_agg(t ORDER BY t.sort_order ASC, t.created_at ASC)
  INTO result FROM public.teachers t;
  RETURN COALESCE(result, '[]'::json);
END; $$;

-- 7. GET ALL BOOKINGS (ADMIN)
CREATE OR REPLACE FUNCTION get_teacher_bookings(pass_code text)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean; result json;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN '[]'::json; END IF;
  SELECT json_agg(
    json_build_object(
      'id', b.id, 'teacher_id', b.teacher_id, 'teacher_name', t.name,
      'day_of_week', b.day_of_week, 'slot_start', b.slot_start,
      'student_name', b.student_name, 'student_phone', b.student_phone,
      'message', b.message, 'status', b.status, 'created_at', b.created_at
    ) ORDER BY b.created_at DESC)
  INTO result
  FROM public.teacher_bookings b JOIN public.teachers t ON t.id = b.teacher_id;
  RETURN COALESCE(result, '[]'::json);
END; $$;

-- 8. UPDATE BOOKING STATUS (ADMIN)
CREATE OR REPLACE FUNCTION update_booking_status(pass_code text, p_id bigint, p_status text)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  UPDATE public.teacher_bookings SET status = p_status WHERE id = p_id;
  RETURN true;
END; $$;

-- 9. SUBMIT TEACHER REVIEW (PUBLIC)
CREATE OR REPLACE FUNCTION submit_teacher_review(
  p_teacher_id bigint, p_reviewer_name text, p_rating integer, p_message text
)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF length(trim(p_message)) < 5 THEN RETURN false; END IF;
  INSERT INTO public.teacher_reviews (teacher_id, reviewer_name, rating, message)
  VALUES (p_teacher_id, p_reviewer_name, LEAST(GREATEST(p_rating, 1), 5), p_message);
  RETURN true;
END; $$;

-- 10. GET TEACHER REVIEWS ADMIN
CREATE OR REPLACE FUNCTION get_teacher_reviews_admin(pass_code text)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean; result json;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN '[]'::json; END IF;
  SELECT json_agg(
    json_build_object(
      'id', r.id, 'teacher_id', r.teacher_id, 'teacher_name', t.name,
      'reviewer_name', r.reviewer_name, 'rating', r.rating,
      'message', r.message, 'is_approved', r.is_approved, 'created_at', r.created_at
    ) ORDER BY r.created_at DESC)
  INTO result
  FROM public.teacher_reviews r JOIN public.teachers t ON t.id = r.teacher_id;
  RETURN COALESCE(result, '[]'::json);
END; $$;

-- 11. APPROVE TEACHER REVIEW (ADMIN)
CREATE OR REPLACE FUNCTION approve_teacher_review(pass_code text, p_id bigint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  UPDATE public.teacher_reviews SET is_approved = true WHERE id = p_id;
  RETURN true;
END; $$;

-- 12. DELETE TEACHER REVIEW (ADMIN)
CREATE OR REPLACE FUNCTION delete_teacher_review(pass_code text, p_id bigint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  DELETE FROM public.teacher_reviews WHERE id = p_id;
  RETURN true;
END; $$;

-- GRANTS
GRANT EXECUTE ON FUNCTION get_teachers_public() TO anon;
GRANT EXECUTE ON FUNCTION get_teacher_by_slug(text) TO anon;
GRANT EXECUTE ON FUNCTION add_teacher(text,text,text,text,text,text[],text,integer,integer,text[],jsonb,text,integer) TO anon;
GRANT EXECUTE ON FUNCTION update_teacher(text,bigint,text,text,text,text,text[],text,integer,integer,text[],jsonb,text,integer,boolean) TO anon;
GRANT EXECUTE ON FUNCTION delete_teacher(text,bigint) TO anon;
GRANT EXECUTE ON FUNCTION get_teachers_admin(text) TO anon;
GRANT EXECUTE ON FUNCTION get_teacher_bookings(text) TO anon;
GRANT EXECUTE ON FUNCTION update_booking_status(text,bigint,text) TO anon;
GRANT EXECUTE ON FUNCTION submit_teacher_review(bigint,text,integer,text) TO anon;
GRANT EXECUTE ON FUNCTION get_teacher_reviews_admin(text) TO anon;
GRANT EXECUTE ON FUNCTION approve_teacher_review(text,bigint) TO anon;
GRANT EXECUTE ON FUNCTION delete_teacher_review(text,bigint) TO anon;

-- ══════════════════════════════════════════════════════════════
-- SLOT REFERENCE: 16 slots (Sat-Wed, 7:00 AM - 10:50 PM, 50 min class + 10 min break)
-- Slot 1:  07:00 – 07:50    Slot 9:  15:00 – 15:50 (03:00 PM)
-- Slot 2:  08:00 – 08:50    Slot 10: 16:00 – 16:50 (04:00 PM)
-- Slot 3:  09:00 – 09:50    Slot 11: 17:00 – 17:50 (05:00 PM)
-- Slot 4:  10:00 – 10:50    Slot 12: 18:00 – 18:50 (06:00 PM)
-- Slot 5:  11:00 – 11:50    Slot 13: 19:00 – 19:50 (07:00 PM)
-- Slot 6:  12:00 – 12:50    Slot 14: 20:00 – 20:50 (08:00 PM)
-- Slot 7:  13:00 – 13:50 (01:00 PM)  Slot 15: 21:00 – 21:50 (09:00 PM)
-- Slot 8:  14:00 – 14:50 (02:00 PM)  Slot 16: 22:00 – 22:50 (10:00 PM)
-- ══════════════════════════════════════════════════════════════
