-- ══════════════════════════════════════════════════════════════
-- GIC TEACHER MARKETPLACE UPGRADE — Database Schema Migration
-- Run this in Supabase SQL Editor
-- ══════════════════════════════════════════════════════════════

-- 1. Ensure new marketplace columns exist on teacher_applications
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS gender text DEFAULT 'male';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS monthly_fee text DEFAULT 'আলোচনা সাপেক্ষে';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS hourly_rate text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS demo_video_url text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS available_days text[] DEFAULT '{}';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS is_verified boolean DEFAULT true;

-- 2. Ensure new marketplace columns exist on teachers table
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS gender text DEFAULT 'male';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS monthly_fee text DEFAULT 'আলোচনা সাপেক্ষে';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS hourly_rate text DEFAULT '';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS demo_video_url text DEFAULT '';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS available_days text[] DEFAULT '{}';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS is_verified boolean DEFAULT true;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS total_reviews integer DEFAULT 0;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS avg_rating numeric(3,2) DEFAULT 5.0;

-- 3. Update public RLS policies for smooth marketplace operation
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "teachers_public_read" ON public.teachers;
CREATE POLICY "teachers_public_read" ON public.teachers FOR SELECT USING (true);

-- Ensure public can book trial classes
CREATE TABLE IF NOT EXISTS public.teacher_bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id bigint REFERENCES public.teachers(id) ON DELETE CASCADE,
  student_name text NOT NULL,
  student_phone text NOT NULL,
  student_msg text DEFAULT '',
  slot_day text DEFAULT '',
  slot_time text DEFAULT '',
  status text DEFAULT 'pending',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.teacher_bookings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bookings_public_insert" ON public.teacher_bookings;
CREATE POLICY "bookings_public_insert" ON public.teacher_bookings FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "bookings_public_select" ON public.teacher_bookings;
CREATE POLICY "bookings_public_select" ON public.teacher_bookings FOR SELECT USING (true);
