-- =====================================================================
-- 📊 GIC Analytics Setup Script (Supabase SQL Editor)
-- Copy and paste this entire script into your Supabase SQL Editor and click RUN.
-- =====================================================================

-- 1. Create table for events log
create table if not exists analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null, -- 'pageview' or 'whatsapp_click'
  page text not null,       -- e.g. 'home', 'courses', 'mini-courses'
  country text default 'Unknown',
  city text default 'Unknown',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
alter table analytics_events enable row level security;

-- Policy: Allow public to insert events (tracking from clients)
create policy "Allow public inserts" on analytics_events
  for insert with check (true);

-- Policy: Disallow anyone from reading table rows directly (hides data)
create policy "Disable public reads" on analytics_events
  for select using (false);

-- 3. Create the secure SQL function to query analytics summaries
-- Only authorized requests providing the correct password can view stats.
create or replace function get_analytics_summary(pass_code text)
returns json
security definer
language plpgsql
as $$
declare
  result json;
  expected_password text := 'gicadmin786'; -- Replace with your desired dashboard password
begin
  -- Validate password
  if pass_code != expected_password then
    raise exception 'Unauthorized: Incorrect password provided.';
  end if;

  select json_build_object(
    -- Today's views (Bangladesh Time Zone: Asia/Dhaka)
    'today_views', (
      select count(*) 
      from analytics_events 
      where event_type = 'pageview' 
        and created_at >= (timezone('Asia/Dhaka', now()))::date
    ),
    -- Today's whatsapp clicks (Bangladesh Time Zone)
    'today_wa_clicks', (
      select count(*) 
      from analytics_events 
      where event_type = 'whatsapp_click' 
        and created_at >= (timezone('Asia/Dhaka', now()))::date
    ),
    -- Top Visited Pages (All time)
    'top_pages', (
      select json_agg(t) from (
        select page, count(*) as count 
        from analytics_events 
        where event_type = 'pageview' 
        group by page 
        order by count desc 
        limit 8
      ) t
    ),
    -- Top WhatsApp sources (All time)
    'top_wa_pages', (
      select json_agg(t) from (
        select page, count(*) as count 
        from analytics_events 
        where event_type = 'whatsapp_click' 
        group by page 
        order by count desc 
        limit 8
      ) t
    ),
    -- Top visitor regions (All time)
    'top_regions', (
      select json_agg(t) from (
        select country, city, count(*) as count 
        from analytics_events 
        group by country, city 
        order by count desc 
        limit 8
      ) t
    ),
    -- Last 7 Days Daily Traffic Chart (Bangladesh Time Zone grouping)
    'daily_traffic', (
      select json_agg(t) from (
        select 
          (timezone('Asia/Dhaka', created_at))::date::text as date,
          count(case when event_type = 'pageview' then 1 end) as views,
          count(case when event_type = 'whatsapp_click' then 1 end) as wa_clicks
        from analytics_events
        where created_at >= (timezone('Asia/Dhaka', now()))::date - interval '7 days'
        group by (timezone('Asia/Dhaka', created_at))::date
        order by (timezone('Asia/Dhaka', created_at))::date asc
      ) t
    )
  ) into result;

  return result;
end;
$$;
