-- =====================================================================
-- 📊 GIC Analytics Setup Script (Supabase SQL Editor) — COMPLETE v2
-- Copy and paste this entire script into your Supabase SQL Editor and click RUN.
-- =====================================================================

-- 1. Create table for analytics events (with ALL required columns)
create table if not exists analytics_events (
  id               bigint generated by default as identity primary key,
  event_type       text not null,      -- 'pageview', 'whatsapp_click', 'page_time'
  page             text not null,      -- e.g. 'home', 'courses', 'free-courses'
  country          text default 'Unknown',
  city             text default 'Unknown',
  referrer_source  text default 'direct',  -- 'facebook','youtube','google','direct', etc.
  referrer_url     text default '',
  utm_source       text default '',
  utm_medium       text default '',
  utm_campaign     text default '',
  time_on_page     integer default 0,  -- seconds (for page_time events)
  created_at       timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Add missing columns if table already exists (safe migration)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name='analytics_events' and column_name='referrer_source') then
    alter table analytics_events add column referrer_source text default 'direct';
  end if;
  if not exists (select 1 from information_schema.columns where table_name='analytics_events' and column_name='referrer_url') then
    alter table analytics_events add column referrer_url text default '';
  end if;
  if not exists (select 1 from information_schema.columns where table_name='analytics_events' and column_name='utm_source') then
    alter table analytics_events add column utm_source text default '';
  end if;
  if not exists (select 1 from information_schema.columns where table_name='analytics_events' and column_name='utm_medium') then
    alter table analytics_events add column utm_medium text default '';
  end if;
  if not exists (select 1 from information_schema.columns where table_name='analytics_events' and column_name='utm_campaign') then
    alter table analytics_events add column utm_campaign text default '';
  end if;
  if not exists (select 1 from information_schema.columns where table_name='analytics_events' and column_name='time_on_page') then
    alter table analytics_events add column time_on_page integer default 0;
  end if;
end
$$;

-- 3. Enable Row Level Security (RLS)
alter table analytics_events enable row level security;

-- 4. Policies (drop and recreate to avoid conflicts)
drop policy if exists "Allow public inserts" on analytics_events;
drop policy if exists "Disable public reads" on analytics_events;

-- Allow anyone to insert (for client-side tracking)
create policy "Allow public inserts" on analytics_events
  for insert with check (true);

-- Block direct table reads (data only via secure function)
create policy "Disable public reads" on analytics_events
  for select using (false);

-- 5. Create the COMPLETE secure analytics function
-- Dashboard uses: today_views, today_wa_clicks, top_pages, top_wa_pages,
-- top_regions, daily_traffic, traffic_sources, traffic_sources_today,
-- page_time_stats, page_time_today, today_events, utm_campaigns,
-- top_pages_today, new_logins_today
create or replace function get_analytics_summary(pass_code text)
returns json
security definer
language plpgsql
as $$
declare
  result json;
  expected_password text := 'gicadmin786';  -- Dashboard login password
begin
  -- Validate password
  if pass_code != expected_password then
    raise exception 'Unauthorized: Incorrect password provided.';
  end if;

  select json_build_object(

    -- ── TODAY STATS (Bangladesh Time UTC+6) ──────────────────────────────
    'today_views', (
      select count(*)
      from analytics_events
      where event_type = 'pageview'
        and (created_at AT TIME ZONE 'Asia/Dhaka')::date = (now() AT TIME ZONE 'Asia/Dhaka')::date
    ),

    'today_wa_clicks', (
      select count(*)
      from analytics_events
      where event_type = 'whatsapp_click'
        and (created_at AT TIME ZONE 'Asia/Dhaka')::date = (now() AT TIME ZONE 'Asia/Dhaka')::date
    ),

    -- ── TOP PAGES (All time) ─────────────────────────────────────────────
    'top_pages', (
      select json_agg(t) from (
        select page, count(*) as count,
          round(avg(case when event_type='page_time' then time_on_page else null end)) as avg_seconds
        from analytics_events
        where event_type in ('pageview','page_time')
        group by page
        order by count desc
        limit 8
      ) t
    ),

    -- ── TODAY TOP PAGES ──────────────────────────────────────────────────
    'top_pages_today', (
      select json_agg(t) from (
        select page, count(*) as count,
          round(avg(case when event_type='page_time' then time_on_page else null end)) as avg_seconds
        from analytics_events
        where event_type in ('pageview','page_time')
          and (created_at AT TIME ZONE 'Asia/Dhaka')::date = (now() AT TIME ZONE 'Asia/Dhaka')::date
        group by page
        order by count desc
        limit 8
      ) t
    ),

    -- ── TOP WA PAGES ─────────────────────────────────────────────────────
    'top_wa_pages', (
      select json_agg(t) from (
        select page, count(*) as count
        from analytics_events
        where event_type = 'whatsapp_click'
        group by page
        order by count desc
        limit 8
      ) t
    ),

    -- ── TOP REGIONS ──────────────────────────────────────────────────────
    'top_regions', (
      select json_agg(t) from (
        select country, city, count(*) as count
        from analytics_events
        where event_type = 'pageview'
        group by country, city
        order by count desc
        limit 10
      ) t
    ),

    -- ── DAILY TRAFFIC (Last 7 days, Bangladesh time) ─────────────────────
    'daily_traffic', (
      select json_agg(t) from (
        select
          (created_at AT TIME ZONE 'Asia/Dhaka')::date::text as date,
          count(case when event_type = 'pageview' then 1 end) as views,
          count(case when event_type = 'whatsapp_click' then 1 end) as wa_clicks
        from analytics_events
        where created_at >= now() - interval '7 days'
        group by (created_at AT TIME ZONE 'Asia/Dhaka')::date
        order by (created_at AT TIME ZONE 'Asia/Dhaka')::date asc
      ) t
    ),

    -- ── TRAFFIC SOURCES (All time) ───────────────────────────────────────
    'traffic_sources', (
      select json_agg(t) from (
        select
          coalesce(nullif(referrer_source,''),'direct') as source,
          count(*) as count
        from analytics_events
        where event_type = 'pageview'
        group by source
        order by count desc
        limit 10
      ) t
    ),

    -- ── TRAFFIC SOURCES TODAY ────────────────────────────────────────────
    'traffic_sources_today', (
      select json_agg(t) from (
        select
          coalesce(nullif(referrer_source,''),'direct') as source,
          count(*) as count
        from analytics_events
        where event_type = 'pageview'
          and (created_at AT TIME ZONE 'Asia/Dhaka')::date = (now() AT TIME ZONE 'Asia/Dhaka')::date
        group by source
        order by count desc
        limit 10
      ) t
    ),

    -- ── PAGE TIME STATS (All time avg) ───────────────────────────────────
    'page_time_stats', (
      select json_agg(t) from (
        select page,
          round(avg(time_on_page)) as avg_seconds,
          count(*) as sessions
        from analytics_events
        where event_type = 'page_time'
          and time_on_page > 0
        group by page
        order by avg_seconds desc
        limit 8
      ) t
    ),

    -- ── PAGE TIME TODAY ──────────────────────────────────────────────────
    'page_time_today', (
      select json_agg(t) from (
        select page,
          round(avg(time_on_page)) as avg_seconds,
          count(*) as sessions
        from analytics_events
        where event_type = 'page_time'
          and time_on_page > 0
          and (created_at AT TIME ZONE 'Asia/Dhaka')::date = (now() AT TIME ZONE 'Asia/Dhaka')::date
        group by page
        order by avg_seconds desc
        limit 8
      ) t
    ),

    -- ── TODAY EVENTS TIMELINE (last 50) ──────────────────────────────────
    'today_events', (
      select json_agg(t) from (
        select
          event_type,
          page,
          coalesce(nullif(referrer_source,''),'direct') as source,
          country,
          city,
          created_at
        from analytics_events
        where (created_at AT TIME ZONE 'Asia/Dhaka')::date = (now() AT TIME ZONE 'Asia/Dhaka')::date
        order by created_at desc
        limit 50
      ) t
    ),

    -- ── UTM CAMPAIGNS ────────────────────────────────────────────────────
    'utm_campaigns', (
      select json_agg(t) from (
        select
          coalesce(nullif(utm_campaign,''),'(no campaign)') as campaign,
          coalesce(nullif(utm_source,''),'direct') as source,
          coalesce(nullif(utm_medium,''),'none') as medium,
          count(*) as visits
        from analytics_events
        where event_type = 'pageview'
          and utm_source != ''
        group by campaign, source, medium
        order by visits desc
        limit 20
      ) t
    )

  ) into result;

  return result;
end;
$$;
