-- =====================================================================
-- 🎓 GIC Students & Progress Tracking Setup Script
-- Copy and paste this into your Supabase SQL Editor and click RUN.
-- =====================================================================

-- 1. Create the students table
create table if not exists students (
  id bigint generated by default as identity primary key,
  phone text unique not null,
  student_id text unique not null,
  xp integer default 0,
  completed_chapters jsonb default '[]'::jsonb,
  streak integer default 0,
  last_visit text default '',
  created_at timestamp with time zone default timezone('Asia/Dhaka', now()) not null,
  updated_at timestamp with time zone default timezone('Asia/Dhaka', now()) not null
);

-- 2. Enable Row Level Security (RLS)
alter table students enable row level security;

-- Policy: Allow public to insert (for creating new IDs)
create policy "Allow public inserts" on students
  for insert with check (true);

-- Policy: Allow public to read their own data (based on student_id/phone check handled by function)
-- We will use SECURITY DEFINER functions instead of complex RLS for simplicity in this case.
create policy "Allow public reads" on students
  for select using (true);
  
create policy "Allow public updates" on students
  for update using (true);

-- 3. Function to login or create a new student
create or replace function login_or_create_student(p_phone text)
returns json
security definer
language plpgsql
as $$
declare
  v_student record;
  v_new_student_id text;
  v_count int;
  result json;
begin
  -- Check if student already exists
  select * into v_student from students where phone = p_phone limit 1;
  
  if found then
    -- Existing student: return their data
    select json_build_object(
      'status', 'success',
      'is_new', false,
      'student_id', v_student.student_id,
      'phone', v_student.phone,
      'xp', v_student.xp,
      'completed_chapters', v_student.completed_chapters,
      'streak', v_student.streak,
      'last_visit', v_student.last_visit
    ) into result;
  else
    -- New student: generate a unique ID
    -- Format: GIC-XXXX (where XXXX is a random number)
    loop
      v_new_student_id := 'GIC-' || lpad(floor(random() * 90000 + 10000)::text, 5, '0');
      select count(*) into v_count from students where student_id = v_new_student_id;
      exit when v_count = 0; -- ID is unique
    end loop;
    
    -- Insert new student
    insert into students (phone, student_id)
    values (p_phone, v_new_student_id)
    returning * into v_student;
    
    select json_build_object(
      'status', 'success',
      'is_new', true,
      'student_id', v_student.student_id,
      'phone', v_student.phone,
      'xp', v_student.xp,
      'completed_chapters', v_student.completed_chapters,
      'streak', v_student.streak,
      'last_visit', v_student.last_visit
    ) into result;
  end if;
  
  return result;
end;
$$;

-- 4. Function to sync progress
create or replace function sync_student_progress(
  p_student_id text,
  p_xp integer,
  p_completed jsonb,
  p_streak integer,
  p_last_visit text
)
returns json
security definer
language plpgsql
as $$
declare
  v_updated record;
  result json;
begin
  update students
  set 
    xp = p_xp,
    completed_chapters = p_completed,
    streak = p_streak,
    last_visit = p_last_visit,
    updated_at = timezone('Asia/Dhaka', now())
  where student_id = p_student_id
  returning * into v_updated;
  
  if found then
    select json_build_object('status', 'success', 'message', 'Progress synced') into result;
  else
    select json_build_object('status', 'error', 'message', 'Student not found') into result;
  end if;
  
  return result;
end;
$$;

-- 5. Function for Admin Dashboard to get student list
create or replace function get_students_list(pass_code text)
returns json
security definer
language plpgsql
as $$
declare
  result json;
  expected_password text := 'gicadmin786'; -- Should match admin password in config
begin
  -- Validate password
  if pass_code != expected_password then
    raise exception 'Unauthorized: Incorrect password provided.';
  end if;

  select json_agg(t) from (
    select 
      student_id,
      phone,
      xp,
      jsonb_array_length(completed_chapters) as chapters_completed_count,
      streak,
      to_char(created_at, 'DD Mon YYYY, HH:MI AM') as join_date,
      to_char(updated_at, 'DD Mon YYYY, HH:MI AM') as last_active
    from students
    order by updated_at desc
  ) t into result;

  return coalesce(result, '[]'::json);
end;
$$;
