-- =====================================================================
-- 📊 GIC Complete Analytics Setup v3 — Supabase SQL Editor
-- Run this ENTIRE script in Supabase SQL Editor to apply all changes.
-- Safe to run multiple times — uses IF NOT EXISTS everywhere.
-- =====================================================================

-- ── 1. ANALYTICS EVENTS TABLE ────────────────────────────────────────
create table if not exists analytics_events (
  id             bigint generated by default as identity primary key,
  event_type     text not null,        -- 'pageview', 'whatsapp_click', 'page_time'
  page           text not null,        -- 'home', 'courses', 'free-courses', etc.
  country        text default 'Unknown',
  city           text default 'Unknown',
  ip_address     text default '',      -- visitor IP address
  student_email  text default '',      -- linked Gmail (if logged in)
  referrer_source text default 'direct',
  referrer_url   text default '',
  utm_source     text default '',
  utm_medium     text default '',
  utm_campaign   text default '',
  time_on_page   integer default 0,    -- seconds (page_time events only)
  created_at     timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Safe migration: add any missing columns
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name='analytics_events' and column_name='ip_address') then
    alter table analytics_events add column ip_address text default '';
  end if;
  if not exists (select 1 from information_schema.columns where table_name='analytics_events' and column_name='student_email') then
    alter table analytics_events add column student_email text default '';
  end if;
  if not exists (select 1 from information_schema.columns where table_name='analytics_events' and column_name='referrer_source') then
    alter table analytics_events add column referrer_source text default 'direct';
  end if;
  if not exists (select 1 from information_schema.columns where table_name='analytics_events' and column_name='referrer_url') then
    alter table analytics_events add column referrer_url text default '';
  end if;
  if not exists (select 1 from information_schema.columns where table_name='analytics_events' and column_name='utm_source') then
    alter table analytics_events add column utm_source text default '';
  end if;
  if not exists (select 1 from information_schema.columns where table_name='analytics_events' and column_name='utm_medium') then
    alter table analytics_events add column utm_medium text default '';
  end if;
  if not exists (select 1 from information_schema.columns where table_name='analytics_events' and column_name='utm_campaign') then
    alter table analytics_events add column utm_campaign text default '';
  end if;
  if not exists (select 1 from information_schema.columns where table_name='analytics_events' and column_name='time_on_page') then
    alter table analytics_events add column time_on_page integer default 0;
  end if;
end
$$;

-- ── 2. COURSE COMMENTS TABLE ─────────────────────────────────────────
create table if not exists course_comments (
  id          bigint generated by default as identity primary key,
  course_id   integer not null,
  name        text not null default 'পাঠক',
  message     text not null,
  rating      integer default 5 check (rating between 1 and 5),
  student_id  text default '',     -- GIC student ID if logged in
  student_email text default '',   -- Gmail if logged in
  ip_address  text default '',
  country     text default '',
  created_at  timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ── 3. INSTITUTION REVIEWS TABLE (if not exists) ─────────────────────
create table if not exists institution_reviews (
  id         bigint generated by default as identity primary key,
  name       text not null default 'এক শিক্ষার্থী',
  message    text not null,
  stars      integer default 5 check (stars between 1 and 5),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ── 4. ROW LEVEL SECURITY ────────────────────────────────────────────
alter table analytics_events  enable row level security;
alter table course_comments   enable row level security;
alter table institution_reviews enable row level security;

-- Drop and recreate all policies cleanly
drop policy if exists "Allow public inserts"          on analytics_events;
drop policy if exists "Disable public reads"          on analytics_events;
drop policy if exists "Allow public comment inserts"  on course_comments;
drop policy if exists "Disable direct comment reads"  on course_comments;
drop policy if exists "Allow public review inserts"   on institution_reviews;
drop policy if exists "Allow review reads"            on institution_reviews;

-- analytics_events: public can insert, not read
create policy "Allow public inserts"   on analytics_events for insert with check (true);
create policy "Disable public reads"   on analytics_events for select using (false);

-- course_comments: public can insert, can read (to show on site)
create policy "Allow public comment inserts" on course_comments for insert with check (true);
create policy "Allow course comment reads"   on course_comments for select using (true);

-- institution_reviews: public insert + read
create policy "Allow public review inserts"  on institution_reviews for insert with check (true);
create policy "Allow review reads"           on institution_reviews for select using (true);

-- ── 5. MAIN ANALYTICS SUMMARY FUNCTION ──────────────────────────────
create or replace function get_analytics_summary(pass_code text)
returns json
security definer
language plpgsql
as $$
declare
  result json;
  expected_password text := 'gicadmin786';
begin
  if pass_code != expected_password then
    raise exception 'Unauthorized';
  end if;

  select json_build_object(

    -- ── TODAY (Bangladesh UTC+6) ──────────────────────────────────
    'today_views', (
      select count(*) from analytics_events
      where event_type = 'pageview'
        and (created_at at time zone 'Asia/Dhaka')::date = (now() at time zone 'Asia/Dhaka')::date
    ),
    'today_wa_clicks', (
      select count(*) from analytics_events
      where event_type = 'whatsapp_click'
        and (created_at at time zone 'Asia/Dhaka')::date = (now() at time zone 'Asia/Dhaka')::date
    ),
    'today_new_logins', (
      select count(distinct student_email) from analytics_events
      where event_type = 'pageview'
        and student_email != ''
        and (created_at at time zone 'Asia/Dhaka')::date = (now() at time zone 'Asia/Dhaka')::date
    ),

    -- ── TODAY EVENTS TIMELINE (last 100) ─────────────────────────
    'today_events', (
      select json_agg(t) from (
        select
          event_type,
          page,
          coalesce(nullif(referrer_source,''), 'direct') as source,
          country, city,
          coalesce(nullif(ip_address,''), '—') as ip_address,
          coalesce(nullif(student_email,''), '') as student_email,
          created_at
        from analytics_events
        where (created_at at time zone 'Asia/Dhaka')::date = (now() at time zone 'Asia/Dhaka')::date
        order by created_at desc
        limit 100
      ) t
    ),

    -- ── TOP PAGES ────────────────────────────────────────────────
    'top_pages', (
      select json_agg(t) from (
        select page, count(*) as count,
          round(avg(case when event_type='page_time' and time_on_page>0 then time_on_page end)) as avg_seconds
        from analytics_events
        where event_type in ('pageview','page_time')
        group by page order by count desc limit 8
      ) t
    ),
    'top_pages_today', (
      select json_agg(t) from (
        select page, count(*) as count,
          round(avg(case when event_type='page_time' and time_on_page>0 then time_on_page end)) as avg_seconds
        from analytics_events
        where event_type in ('pageview','page_time')
          and (created_at at time zone 'Asia/Dhaka')::date = (now() at time zone 'Asia/Dhaka')::date
        group by page order by count desc limit 8
      ) t
    ),

    -- ── TOP WA PAGES ─────────────────────────────────────────────
    'top_wa_pages', (
      select json_agg(t) from (
        select page, count(*) as count from analytics_events
        where event_type='whatsapp_click'
        group by page order by count desc limit 8
      ) t
    ),

    -- ── TOP REGIONS ──────────────────────────────────────────────
    'top_regions', (
      select json_agg(t) from (
        select country, city, count(*) as count from analytics_events
        where event_type='pageview'
        group by country, city order by count desc limit 10
      ) t
    ),

    -- ── DAILY TRAFFIC (7 days) ───────────────────────────────────
    'daily_traffic', (
      select json_agg(t) from (
        select
          (created_at at time zone 'Asia/Dhaka')::date::text as date,
          count(case when event_type='pageview' then 1 end) as views,
          count(case when event_type='whatsapp_click' then 1 end) as wa_clicks
        from analytics_events
        where created_at >= now() - interval '7 days'
        group by (created_at at time zone 'Asia/Dhaka')::date
        order by 1 asc
      ) t
    ),

    -- ── TRAFFIC SOURCES ──────────────────────────────────────────
    'traffic_sources', (
      select json_agg(t) from (
        select coalesce(nullif(referrer_source,''),'direct') as source, count(*) as count
        from analytics_events where event_type='pageview'
        group by source order by count desc limit 10
      ) t
    ),
    'traffic_sources_today', (
      select json_agg(t) from (
        select coalesce(nullif(referrer_source,''),'direct') as source, count(*) as count
        from analytics_events where event_type='pageview'
          and (created_at at time zone 'Asia/Dhaka')::date = (now() at time zone 'Asia/Dhaka')::date
        group by source order by count desc limit 10
      ) t
    ),

    -- ── PAGE TIME ────────────────────────────────────────────────
    'page_time_stats', (
      select json_agg(t) from (
        select page, round(avg(time_on_page)) as avg_seconds, count(*) as sessions
        from analytics_events where event_type='page_time' and time_on_page>0
        group by page order by avg_seconds desc limit 8
      ) t
    ),
    'page_time_today', (
      select json_agg(t) from (
        select page, round(avg(time_on_page)) as avg_seconds, count(*) as sessions
        from analytics_events where event_type='page_time' and time_on_page>0
          and (created_at at time zone 'Asia/Dhaka')::date = (now() at time zone 'Asia/Dhaka')::date
        group by page order by avg_seconds desc limit 8
      ) t
    ),

    -- ── RECENT UNIQUE VISITORS (with IP) ─────────────────────────
    'recent_visitors', (
      select json_agg(t) from (
        select distinct on (ip_address)
          ip_address, country, city,
          coalesce(nullif(referrer_source,''),'direct') as source,
          coalesce(nullif(student_email,''), '') as student_email,
          max(created_at) as last_seen,
          count(*) over (partition by ip_address) as page_count
        from analytics_events
        where event_type='pageview' and ip_address != ''
        group by ip_address, country, city, referrer_source, student_email
        order by ip_address, last_seen desc
        limit 50
      ) t
    )

  ) into result;
  return result;
end;
$$;

-- ── 6. GET STUDENT ACTIVITY (Gmail-linked) ───────────────────────────
create or replace function get_student_activity(p_email text, pass_code text)
returns json
security definer
language plpgsql
as $$
declare
  result json;
  expected_password text := 'gicadmin786';
begin
  if pass_code != expected_password then
    raise exception 'Unauthorized';
  end if;

  select json_build_object(
    'events', (
      select json_agg(t) from (
        select event_type, page,
          coalesce(nullif(ip_address,''), '—') as ip_address,
          country, city,
          coalesce(nullif(referrer_source,''),'direct') as source,
          time_on_page, created_at
        from analytics_events
        where lower(student_email) = lower(p_email)
        order by created_at desc
        limit 200
      ) t
    ),
    'summary', (
      select json_build_object(
        'total_pageviews', count(case when event_type='pageview' then 1 end),
        'total_wa_clicks', count(case when event_type='whatsapp_click' then 1 end),
        'avg_time_per_page', round(avg(case when event_type='page_time' and time_on_page>0 then time_on_page end)),
        'first_visit', min(created_at),
        'last_visit', max(created_at),
        'unique_ips', count(distinct ip_address)
      )
      from analytics_events
      where lower(student_email) = lower(p_email)
    ),
    'pages_visited', (
      select json_agg(t) from (
        select page, count(*) as visits,
          round(avg(case when event_type='page_time' and time_on_page>0 then time_on_page end)) as avg_seconds
        from analytics_events
        where lower(student_email) = lower(p_email)
          and event_type in ('pageview','page_time')
        group by page order by visits desc limit 10
      ) t
    )
  ) into result;
  return result;
end;
$$;

-- ── 7. DELETE COURSE COMMENT ─────────────────────────────────────────
create or replace function delete_course_comment(p_id bigint, pass_code text)
returns boolean
security definer
language plpgsql
as $$
declare
  expected_password text := 'gicadmin786';
begin
  if pass_code != expected_password then
    raise exception 'Unauthorized';
  end if;
  delete from course_comments where id = p_id;
  return true;
end;
$$;

-- ── 8. DELETE INSTITUTION REVIEW ─────────────────────────────────────
create or replace function delete_institution_review(p_id bigint, pass_code text)
returns boolean
security definer
language plpgsql
as $$
declare
  expected_password text := 'gicadmin786';
begin
  if pass_code != expected_password then
    raise exception 'Unauthorized';
  end if;
  delete from institution_reviews where id = p_id;
  return true;
end;
$$;
