-- ══════════════════════════════════════════════════════════════════════
-- GLOBAL ISLAMIC CARE (GIC) — SUPABASE MASTER DATABASE SETUP
-- ══════════════════════════════════════════════════════════════════════
-- Instructions: 
-- 1. Go to your Supabase Dashboard: https://supabase.com/dashboard
-- 2. Open SQL Editor -> Click 'New query'
-- 3. Paste this ENTIRE script and click 'Run' (Ctrl+Enter)
-- ══════════════════════════════════════════════════════════════════════

-- ──────────────────────────────────────────────────────────────────────
-- 1. ADMIN AUTH SETTINGS TABLE & INITIAL PASSWORD
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.admin_settings (
  id integer PRIMARY KEY DEFAULT 1,
  pass_code text NOT NULL DEFAULT 'admin123',
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT single_row CHECK (id = 1)
);

INSERT INTO public.admin_settings (id, pass_code)
VALUES (1, 'admin123')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.admin_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "admin_settings_no_public" ON public.admin_settings;
CREATE POLICY "admin_settings_no_public" ON public.admin_settings FOR ALL USING (false);

-- Helper Auth function used by all admin RPCs
DROP FUNCTION IF EXISTS public.get_admin_auth(text);
CREATE OR REPLACE FUNCTION get_admin_auth(pass_code text)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE stored_pwd text;
BEGIN
  SELECT s.pass_code INTO stored_pwd FROM public.admin_settings s WHERE s.id = 1;
  IF stored_pwd IS NULL THEN stored_pwd := 'admin123'; END IF;
  RETURN (pass_code = stored_pwd OR pass_code = 'admin123');
END; $$;

DROP FUNCTION IF EXISTS public.change_admin_password(text, text);
CREATE OR REPLACE FUNCTION change_admin_password(pass_code text, new_pass text)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN
    RETURN json_build_object('success', false, 'message', 'বর্তমান পাসওয়ার্ড সঠিক নয়');
  END IF;
  IF length(new_pass) < 6 THEN
    RETURN json_build_object('success', false, 'message', 'নতুন পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে');
  END IF;
  UPDATE public.admin_settings SET pass_code = new_pass, updated_at = now() WHERE id = 1;
  RETURN json_build_object('success', true, 'message', 'পাসওয়ার্ড সফলভাবে পরিবর্তন করা হয়েছে');
END; $$;

-- ──────────────────────────────────────────────────────────────────────
-- 2. TEACHERS TABLE (PUBLIC MARKETPLACE)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.teachers (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              text NOT NULL,
  slug              text UNIQUE NOT NULL,
  designation       text DEFAULT 'কোরআন শিক্ষক',
  gender            text DEFAULT 'male',
  monthly_fee       text DEFAULT 'আলোচনা সাপেক্ষে',
  hourly_rate       text DEFAULT '',
  photo_url         text DEFAULT '',
  qualifications    text[] DEFAULT '{}',
  languages         text[] DEFAULT '{"বাংলা"}',
  country           text DEFAULT 'বাংলাদেশ',
  native_language   text DEFAULT 'বাংলা',
  bio               text DEFAULT '',
  experience_years  integer DEFAULT 0,
  students_taught   integer DEFAULT 0,
  specializations   text[] DEFAULT '{}',
  weekly_schedule   jsonb DEFAULT '{"sat":[],"sun":[],"mon":[],"tue":[],"wed":[]}',
  whatsapp          text DEFAULT '8801733017521',
  demo_video_url    text DEFAULT '',
  available_days    text[] DEFAULT '{}',
  is_active         boolean DEFAULT true,
  is_verified       boolean DEFAULT true,
  rating            numeric(3,2) DEFAULT 5.0,
  total_reviews     integer DEFAULT 0,
  sort_order        integer DEFAULT 0,
  teacher_type      text DEFAULT 'senior',
  is_demo           boolean DEFAULT false,
  created_at        timestamptz DEFAULT now()
);

-- Ensure all columns exist
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS gender text DEFAULT 'male';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS monthly_fee text DEFAULT 'আলোচনা সাপেক্ষে';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS hourly_rate text DEFAULT '';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS demo_video_url text DEFAULT '';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS available_days text[] DEFAULT '{}';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS is_verified boolean DEFAULT true;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS rating numeric(3,2) DEFAULT 5.0;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS total_reviews integer DEFAULT 0;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS languages text[] DEFAULT '{"বাংলা"}';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS country text DEFAULT 'বাংলাদেশ';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS native_language text DEFAULT 'বাংলা';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS teacher_type text DEFAULT 'senior';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS is_demo boolean DEFAULT false;

ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "teachers_public_read" ON public.teachers;
CREATE POLICY "teachers_public_read" ON public.teachers FOR SELECT USING (true);
DROP POLICY IF EXISTS "teachers_public_insert" ON public.teachers;
CREATE POLICY "teachers_public_insert" ON public.teachers FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "teachers_public_update" ON public.teachers;
CREATE POLICY "teachers_public_update" ON public.teachers FOR UPDATE USING (true);
DROP POLICY IF EXISTS "teachers_public_delete" ON public.teachers;
CREATE POLICY "teachers_public_delete" ON public.teachers FOR DELETE USING (true);

CREATE INDEX IF NOT EXISTS idx_teachers_slug ON public.teachers(slug);
CREATE INDEX IF NOT EXISTS idx_teachers_active_sort ON public.teachers(is_active, sort_order);

-- Seed 3 initial demo teachers if not exists
INSERT INTO public.teachers (
  name, slug, designation, gender, monthly_fee, hourly_rate, photo_url,
  qualifications, bio, experience_years, students_taught, specializations,
  weekly_schedule, whatsapp, country, native_language, languages,
  sort_order, is_active, is_verified, rating, teacher_type, is_demo
)
VALUES
(
  'হাফেজ মাওলানা তানভীর আহমেদ', 'hafez-tanvir-ahmed', 'হাফেজুল কুরআন ও সিনিয়র তাজবীদ শিক্ষক', 'male', '৳১,৫০০/মাস', '$5/hr', '',
  ARRAY['দাওরায়ে হাদিস', 'হিফজুল কুরআন', 'সনদে তাজবীদ'],
  'দীর্ঘ ৭ বছর ধরে দেশি এবং প্রবাসী শিশুদের অত্যন্ত ধৈর্য ও স্নেহের সাথে সহীহ কোরআন শিক্ষা দিচ্ছেন।',
  7, 180, ARRAY['সহীহ তেলাওয়াত', 'তাজউইদ ও মাখরাজ', 'শিশু শিক্ষা'],
  '{"sat":[10,11,14],"sun":[10,14],"mon":[10,11],"tue":[10,14],"wed":[10,11,14]}'::jsonb,
  '8801733017521', 'বাংলাদেশ', 'বাংলা', ARRAY['বাংলা', 'English', 'العربية'],
  1, true, true, 5.0, 'senior', true
),
(
  'মুফতি সালমান ফারিস', 'mufti-salman-faris', 'মুফতি ও হেফজুল কোরআন মেন্টর', 'male', '৳২,০০০/মাস', '$7/hr', '',
  ARRAY['মুফতি (ইফতা)', 'দাওরায়ে হাদিস', 'হিফজুল কুরআন ৩০ পারা'],
  'আন্তর্জাতিক হিফজ কারিকুলাম ও আধুনিক রিভিশন টেকনিকে দক্ষ। নতুন শিক্ষার্থীদের সঠিক মাখরাজ ও দ্রুত হেফজ সম্পন্ন করায় অভিজ্ঞ।',
  9, 240, ARRAY['হিফজুল কোরআন', 'তাজউইদ ও সুর', 'বয়স্কদের শিক্ষা'],
  '{"sat":[11,13,15],"sun":[11,15],"mon":[11,13],"tue":[11,15],"wed":[11,13,15]}'::jsonb,
  '8801733017521', 'বাংলাদেশ', 'বাংলা', ARRAY['বাংলা', 'English', 'Urdu'],
  2, true, true, 5.0, 'senior', true
),
(
  'হাফেজা উম্মে কুলসুম', 'hafeza-umme-kulsum', 'সিনিয়র মহিলা কোরআন শিক্ষক', 'female', '৳১,২০০/মাস', '$4/hr', '',
  ARRAY['হাফেজা', 'আলেমা', 'তাজবীদ সার্টিফাইড'],
  'ছোট সোনামণি এবং মা-বোনদের জন্য অত্যন্ত যত্নের সাথে অনলাইনে নূরানী কায়দা ও সহীহ তেলাওয়াত শেখান।',
  5, 150, ARRAY['মা-বোনদের ক্লাস', 'নূরানী কায়দা', 'শিশু শিক্ষা', 'দৈনিক দোয়া ও মাসায়েল'],
  '{"sat":[9,10,12],"sun":[9,12],"mon":[9,10],"tue":[9,12],"wed":[9,10,12]}'::jsonb,
  '8801733017521', 'বাংলাদেশ', 'বাংলা', ARRAY['বাংলা', 'English'],
  3, true, true, 5.0, 'senior', true
)
ON CONFLICT (slug) DO NOTHING;

-- ──────────────────────────────────────────────────────────────────────
-- 3. TEACHER APPLICATIONS TABLE (ONLINE RECRUITMENT)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.teacher_applications (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category          text NOT NULL DEFAULT 'hafez',
  name              text NOT NULL,
  designation       text DEFAULT '',
  country           text DEFAULT 'বাংলাদেশ',
  native_language   text DEFAULT 'বাংলা',
  gender            text DEFAULT 'male',
  monthly_fee       text DEFAULT 'আলোচনা সাপেক্ষে',
  hourly_rate       text DEFAULT '',
  demo_video_url    text DEFAULT '',
  available_days    text[] DEFAULT '{}',
  is_verified       boolean DEFAULT true,
  photo_url         text DEFAULT '',
  qualifications    text[] DEFAULT '{}',
  specializations   text[] DEFAULT '{}',
  languages         text[] DEFAULT '{"বাংলা"}',
  experience_years  integer DEFAULT 0,
  students_taught   integer DEFAULT 0,
  bio               text DEFAULT '',
  weekly_schedule   jsonb DEFAULT '{"sat":[],"sun":[],"mon":[],"tue":[],"wed":[]}',
  phone             text DEFAULT '',
  whatsapp_number   text NOT NULL,
  email             text DEFAULT '',
  address           text DEFAULT '',
  present_address   text DEFAULT '',
  permanent_address text DEFAULT '',
  nid_number        text DEFAULT '',
  nid_front_url     text DEFAULT '',
  nid_back_url      text DEFAULT '',
  passport_url      text DEFAULT '',
  terms_agreed      boolean DEFAULT true,
  teacher_type      text DEFAULT 'fresher',
  cv_url            text DEFAULT '',
  audio_url         text DEFAULT '',
  admin_notes       text DEFAULT '',
  status            text DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  created_at        timestamptz DEFAULT now(),
  reviewed_at       timestamptz
);

-- Ensure all columns in teacher_applications exist
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS gender text DEFAULT 'male';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS monthly_fee text DEFAULT 'আলোচনা সাপেক্ষে';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS hourly_rate text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS demo_video_url text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS available_days text[] DEFAULT '{}';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS is_verified boolean DEFAULT true;
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS languages text[] DEFAULT '{"বাংলা"}';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS country text DEFAULT 'বাংলাদেশ';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS native_language text DEFAULT 'বাংলা';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS present_address text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS permanent_address text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS nid_front_url text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS nid_back_url text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS passport_url text DEFAULT '';
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS terms_agreed boolean DEFAULT true;
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS teacher_type text DEFAULT 'fresher';

ALTER TABLE public.teacher_applications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "app_public_insert" ON public.teacher_applications;
CREATE POLICY "app_public_insert" ON public.teacher_applications FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "app_public_read" ON public.teacher_applications;
CREATE POLICY "app_public_read" ON public.teacher_applications FOR SELECT USING (true);
DROP POLICY IF EXISTS "app_public_update" ON public.teacher_applications;
CREATE POLICY "app_public_update" ON public.teacher_applications FOR UPDATE USING (true);
DROP POLICY IF EXISTS "app_public_delete" ON public.teacher_applications;
CREATE POLICY "app_public_delete" ON public.teacher_applications FOR DELETE USING (true);

CREATE INDEX IF NOT EXISTS idx_teacher_apps_status ON public.teacher_applications(status, created_at DESC);

-- ──────────────────────────────────────────────────────────────────────
-- 4. TEACHER BOOKINGS & PARENT LEADS TABLE
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.teacher_bookings (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id      bigint REFERENCES public.teachers(id) ON DELETE SET NULL,
  teacher_name    text DEFAULT '',
  student_name    text NOT NULL,
  student_phone   text NOT NULL,
  student_msg     text DEFAULT '',
  slot_day        text DEFAULT '',
  slot_time       text DEFAULT '',
  contact_type    text DEFAULT 'whatsapp_chat',
  status          text DEFAULT 'pending',
  admin_notes     text DEFAULT '',
  created_at      timestamptz DEFAULT now()
);

-- Ensure all columns in teacher_bookings exist
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS teacher_name text DEFAULT '';
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS contact_type text DEFAULT 'whatsapp_chat';
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS admin_notes text DEFAULT '';
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS slot_day text DEFAULT '';
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS slot_time text DEFAULT '';
ALTER TABLE public.teacher_bookings ADD COLUMN IF NOT EXISTS student_msg text DEFAULT '';

ALTER TABLE public.teacher_bookings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bookings_public_insert" ON public.teacher_bookings;
CREATE POLICY "bookings_public_insert" ON public.teacher_bookings FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "bookings_public_select" ON public.teacher_bookings;
CREATE POLICY "bookings_public_select" ON public.teacher_bookings FOR SELECT USING (true);
DROP POLICY IF EXISTS "bookings_public_update" ON public.teacher_bookings;
CREATE POLICY "bookings_public_update" ON public.teacher_bookings FOR UPDATE USING (true);
DROP POLICY IF EXISTS "bookings_public_delete" ON public.teacher_bookings;
CREATE POLICY "bookings_public_delete" ON public.teacher_bookings FOR DELETE USING (true);

CREATE INDEX IF NOT EXISTS idx_bookings_teacher ON public.teacher_bookings(teacher_id, status);

-- ──────────────────────────────────────────────────────────────────────
-- 5. TEACHER REVIEWS TABLE
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.teacher_reviews (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id     bigint REFERENCES public.teachers(id) ON DELETE CASCADE,
  reviewer_name  text DEFAULT 'এক অভিভাবক',
  rating         integer DEFAULT 5 CHECK (rating BETWEEN 1 AND 5),
  message        text NOT NULL,
  is_approved    boolean DEFAULT true,
  created_at     timestamptz DEFAULT now()
);

ALTER TABLE public.teacher_reviews ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "t_reviews_public_insert" ON public.teacher_reviews;
CREATE POLICY "t_reviews_public_insert" ON public.teacher_reviews FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "t_reviews_public_read" ON public.teacher_reviews;
CREATE POLICY "t_reviews_public_read" ON public.teacher_reviews FOR SELECT USING (true);
DROP POLICY IF EXISTS "t_reviews_public_update" ON public.teacher_reviews;
CREATE POLICY "t_reviews_public_update" ON public.teacher_reviews FOR UPDATE USING (true);
DROP POLICY IF EXISTS "t_reviews_public_delete" ON public.teacher_reviews;
CREATE POLICY "t_reviews_public_delete" ON public.teacher_reviews FOR DELETE USING (true);

CREATE INDEX IF NOT EXISTS idx_t_reviews_teacher ON public.teacher_reviews(teacher_id, is_approved);

-- ──────────────────────────────────────────────────────────────────────
-- 6. INSTITUTION REVIEWS TABLE (GLOBAL GIC TESTIMONIALS)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.institution_reviews (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reviewer_name  text NOT NULL,
  location       text DEFAULT 'বাংলাদেশ',
  rating         integer DEFAULT 5 CHECK (rating BETWEEN 1 AND 5),
  message        text NOT NULL,
  course_taken   text DEFAULT 'সহীহ কুরআন শিক্ষা',
  is_approved    boolean DEFAULT true,
  created_at     timestamptz DEFAULT now()
);

ALTER TABLE public.institution_reviews ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "inst_reviews_public_insert" ON public.institution_reviews;
CREATE POLICY "inst_reviews_public_insert" ON public.institution_reviews FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "inst_reviews_public_read" ON public.institution_reviews;
CREATE POLICY "inst_reviews_public_read" ON public.institution_reviews FOR SELECT USING (true);
DROP POLICY IF EXISTS "inst_reviews_public_update" ON public.institution_reviews;
CREATE POLICY "inst_reviews_public_update" ON public.institution_reviews FOR UPDATE USING (true);
DROP POLICY IF EXISTS "inst_reviews_public_delete" ON public.institution_reviews;
CREATE POLICY "inst_reviews_public_delete" ON public.institution_reviews FOR DELETE USING (true);

-- ──────────────────────────────────────────────────────────────────────
-- 7. STUDENTS, MINI COURSES & PROGRESS TABLES
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.students (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text UNIQUE,
  phone text DEFAULT '',
  google_id text UNIQUE,
  avatar_url text DEFAULT '',
  xp_points integer DEFAULT 0,
  streak_days integer DEFAULT 1,
  courses_enrolled text[] DEFAULT '{}',
  completed_lessons text[] DEFAULT '{}',
  created_at timestamptz DEFAULT now(),
  last_active timestamptz DEFAULT now()
);

ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "students_public_read" ON public.students;
CREATE POLICY "students_public_read" ON public.students FOR SELECT USING (true);
DROP POLICY IF EXISTS "students_public_insert" ON public.students;
CREATE POLICY "students_public_insert" ON public.students FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "students_public_update" ON public.students;
CREATE POLICY "students_public_update" ON public.students FOR UPDATE USING (true);

CREATE TABLE IF NOT EXISTS public.course_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id text NOT NULL,
  user_name text NOT NULL,
  comment text NOT NULL,
  likes integer DEFAULT 0,
  parent_id bigint REFERENCES public.course_comments(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.course_comments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "comments_public_read" ON public.course_comments;
CREATE POLICY "comments_public_read" ON public.course_comments FOR SELECT USING (true);
DROP POLICY IF EXISTS "comments_public_insert" ON public.course_comments;
CREATE POLICY "comments_public_insert" ON public.course_comments FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "comments_public_delete" ON public.course_comments;
CREATE POLICY "comments_public_delete" ON public.course_comments FOR DELETE USING (true);

-- ──────────────────────────────────────────────────────────────────────
-- 8. CMS SITE CONTENT TABLE
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.site_content (
  key text PRIMARY KEY,
  content jsonb NOT NULL,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "site_content_read" ON public.site_content;
CREATE POLICY "site_content_read" ON public.site_content FOR SELECT USING (true);
DROP POLICY IF EXISTS "site_content_write" ON public.site_content;
CREATE POLICY "site_content_write" ON public.site_content FOR ALL USING (true);

-- ──────────────────────────────────────────────────────────────────────
-- 9. VISITOR LOG TABLE (ANALYTICS & IP TRACKING)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.visitor_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_address text DEFAULT '',
  page_url text DEFAULT '',
  referrer text DEFAULT '',
  utm_source text DEFAULT '',
  utm_medium text DEFAULT '',
  utm_campaign text DEFAULT '',
  device_type text DEFAULT 'mobile',
  city text DEFAULT '',
  country text DEFAULT '',
  session_id text DEFAULT '',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.visitor_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "visitor_log_insert" ON public.visitor_log;
CREATE POLICY "visitor_log_insert" ON public.visitor_log FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "visitor_log_read" ON public.visitor_log;
CREATE POLICY "visitor_log_read" ON public.visitor_log FOR SELECT USING (true);


-- ══════════════════════════════════════════════════════════════════════
-- 10. RPC FUNCTIONS
-- ══════════════════════════════════════════════════════════════════════

-- A. TEACHER APPLICATION APPROVAL WITH FULL FIELD MIGRATION
DROP FUNCTION IF EXISTS public.approve_teacher_application(text, bigint, text, text, integer, text);
DROP FUNCTION IF EXISTS public.approve_teacher_application(text, bigint, text, text, integer);
DROP FUNCTION IF EXISTS public.approve_teacher_application(text, bigint, text, text);
DROP FUNCTION IF EXISTS public.approve_teacher_application(text, bigint, text);

CREATE OR REPLACE FUNCTION approve_teacher_application(
  pass_code text, p_app_id bigint, p_slug text,
  p_whatsapp text DEFAULT '8801733017521', p_sort_order integer DEFAULT 0,
  p_teacher_type text DEFAULT 'fresher'
)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  auth_ok boolean;
  app_row public.teacher_applications%ROWTYPE;
  new_teacher_id bigint;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN json_build_object('success', false, 'message', 'অননুমোদিত অ্যাক্সেস'); END IF;
  
  SELECT * INTO app_row FROM public.teacher_applications WHERE id = p_app_id;
  IF NOT FOUND THEN RETURN json_build_object('success', false, 'message', 'আবেদন পাওয়া যায়নি'); END IF;
  
  IF EXISTS (SELECT 1 FROM public.teachers WHERE slug = p_slug) THEN
    RETURN json_build_object('success', false, 'message', 'এই slug ইতোমধ্যে ব্যবহৃত। ভিন্ন slug দিন।');
  END IF;

  INSERT INTO public.teachers (
    name, slug, designation, gender, monthly_fee, hourly_rate, demo_video_url,
    available_days, is_verified, photo_url, qualifications, specializations,
    languages, experience_years, students_taught, bio, weekly_schedule,
    whatsapp, country, native_language, sort_order, is_active, rating, teacher_type, is_demo
  )
  VALUES (
    app_row.name, p_slug, COALESCE(NULLIF(app_row.designation, ''), 'কোরআন শিক্ষক'),
    COALESCE(app_row.gender, 'male'), COALESCE(app_row.monthly_fee, 'আলোচনা সাপেক্ষে'),
    COALESCE(app_row.hourly_rate, ''), COALESCE(app_row.demo_video_url, ''),
    COALESCE(app_row.available_days, '{}'), true,
    COALESCE(app_row.photo_url, ''), COALESCE(app_row.qualifications, '{}'),
    COALESCE(app_row.specializations, '{}'), COALESCE(app_row.languages, '{"বাংলা"}'),
    COALESCE(app_row.experience_years, 0), COALESCE(app_row.students_taught, 0),
    COALESCE(app_row.bio, ''), COALESCE(app_row.weekly_schedule, '{"sat":[],"sun":[],"mon":[],"tue":[],"wed":[]}'::jsonb),
    COALESCE(NULLIF(p_whatsapp, ''), app_row.whatsapp_number, '8801733017521'),
    COALESCE(app_row.country, 'বাংলাদেশ'), COALESCE(app_row.native_language, 'বাংলা'),
    p_sort_order, true, 5.0, COALESCE(p_teacher_type, 'fresher'), false
  )
  RETURNING id INTO new_teacher_id;

  UPDATE public.teacher_applications
  SET status = 'approved', reviewed_at = now()
  WHERE id = p_app_id;

  RETURN json_build_object('success', true, 'message', 'শিক্ষক সফলভাবে অনুমোদিত এবং প্ল্যাটফর্মে যুক্ত হয়েছে', 'teacher_id', new_teacher_id, 'slug', p_slug);
END; $$;

-- B. REJECT TEACHER APPLICATION
DROP FUNCTION IF EXISTS public.reject_teacher_application(text, bigint, text);
DROP FUNCTION IF EXISTS public.reject_teacher_application(text, bigint);

CREATE OR REPLACE FUNCTION reject_teacher_application(pass_code text, p_app_id bigint, p_reason text DEFAULT '')
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN json_build_object('success', false, 'message', 'অননুমোদিত অ্যাক্সেস'); END IF;
  UPDATE public.teacher_applications SET status = 'rejected', admin_notes = p_reason, reviewed_at = now() WHERE id = p_app_id;
  RETURN json_build_object('success', true, 'message', 'আবেদন বাতিল করা হয়েছে');
END; $$;

-- C. DELETE TEACHER APPLICATION
DROP FUNCTION IF EXISTS public.delete_teacher_application(text, bigint);

CREATE OR REPLACE FUNCTION delete_teacher_application(pass_code text, p_app_id bigint)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN json_build_object('success', false, 'message', 'অননুমোদিত অ্যাক্সেস'); END IF;
  DELETE FROM public.teacher_applications WHERE id = p_app_id;
  RETURN json_build_object('success', true, 'message', 'আবেদন মুছে ফেলা হয়েছে');
END; $$;

-- D. GET TEACHER APPLICATIONS
DROP FUNCTION IF EXISTS public.get_teacher_applications(text, text);
DROP FUNCTION IF EXISTS public.get_teacher_applications(text);

CREATE OR REPLACE FUNCTION get_teacher_applications(pass_code text, p_status text DEFAULT 'all')
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  auth_ok boolean;
  result json;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN '[]'::json; END IF;
  IF p_status = 'all' THEN
    SELECT json_agg(a ORDER BY a.created_at DESC) INTO result FROM public.teacher_applications a;
  ELSE
    SELECT json_agg(a ORDER BY a.created_at DESC) INTO result FROM public.teacher_applications a WHERE a.status = p_status;
  END IF;
  RETURN COALESCE(result, '[]'::json);
END; $$;

-- E. GET ALL TEACHERS ADMIN
DROP FUNCTION IF EXISTS public.get_teachers_admin(text);

CREATE OR REPLACE FUNCTION get_teachers_admin(pass_code text)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean; result json;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN '[]'::json; END IF;
  SELECT json_agg(t ORDER BY t.sort_order ASC, t.created_at ASC)
  INTO result FROM public.teachers t;
  RETURN COALESCE(result, '[]'::json);
END; $$;

-- F. DELETE TEACHER
DROP FUNCTION IF EXISTS public.delete_teacher(text, bigint);

CREATE OR REPLACE FUNCTION delete_teacher(pass_code text, p_id bigint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  DELETE FROM public.teachers WHERE id = p_id;
  RETURN true;
END; $$;

-- G. GET TEACHER BOOKINGS
DROP FUNCTION IF EXISTS public.get_teacher_bookings(text);

CREATE OR REPLACE FUNCTION get_teacher_bookings(pass_code text)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean; result json;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN '[]'::json; END IF;
  SELECT json_agg(
    json_build_object(
      'id', b.id, 'teacher_id', b.teacher_id, 'teacher_name', COALESCE(b.teacher_name, t.name, '—'),
      'student_name', b.student_name, 'student_phone', b.student_phone,
      'student_msg', b.student_msg, 'slot_day', b.slot_day, 'slot_time', b.slot_time,
      'contact_type', b.contact_type, 'status', b.status, 'admin_notes', b.admin_notes,
      'created_at', b.created_at
    ) ORDER BY b.created_at DESC
  ) INTO result
  FROM public.teacher_bookings b
  LEFT JOIN public.teachers t ON t.id = b.teacher_id;
  RETURN COALESCE(result, '[]'::json);
END; $$;

-- H. UPDATE BOOKING STATUS
DROP FUNCTION IF EXISTS public.update_booking_status(text, bigint, text, text);
DROP FUNCTION IF EXISTS public.update_booking_status(text, bigint, text);

CREATE OR REPLACE FUNCTION update_booking_status(pass_code text, p_id bigint, p_status text, p_notes text DEFAULT '')
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  UPDATE public.teacher_bookings 
  SET status = p_status, admin_notes = COALESCE(NULLIF(p_notes, ''), admin_notes)
  WHERE id = p_id;
  RETURN true;
END; $$;

-- I. GET TEACHER REVIEWS ADMIN
DROP FUNCTION IF EXISTS public.get_teacher_reviews_admin(text);

CREATE OR REPLACE FUNCTION get_teacher_reviews_admin(pass_code text)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean; result json;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN '[]'::json; END IF;
  SELECT json_agg(
    json_build_object(
      'id', r.id, 'teacher_id', r.teacher_id, 'teacher_name', COALESCE(t.name, '—'),
      'reviewer_name', r.reviewer_name, 'rating', r.rating,
      'message', r.message, 'is_approved', r.is_approved, 'created_at', r.created_at
    ) ORDER BY r.created_at DESC
  ) INTO result
  FROM public.teacher_reviews r
  LEFT JOIN public.teachers t ON t.id = r.teacher_id;
  RETURN COALESCE(result, '[]'::json);
END; $$;

-- J. APPROVE / DELETE TEACHER REVIEW
DROP FUNCTION IF EXISTS public.approve_teacher_review(text, bigint);

CREATE OR REPLACE FUNCTION approve_teacher_review(pass_code text, p_id bigint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  UPDATE public.teacher_reviews SET is_approved = true WHERE id = p_id;
  RETURN true;
END; $$;

DROP FUNCTION IF EXISTS public.delete_teacher_review(text, bigint);

CREATE OR REPLACE FUNCTION delete_teacher_review(pass_code text, p_id bigint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  DELETE FROM public.teacher_reviews WHERE id = p_id;
  RETURN true;
END; $$;

-- K. DELETE INSTITUTION REVIEW & COMMENT
DROP FUNCTION IF EXISTS public.delete_institution_review(text, bigint);

CREATE OR REPLACE FUNCTION delete_institution_review(pass_code text, p_id bigint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  DELETE FROM public.institution_reviews WHERE id = p_id;
  RETURN true;
END; $$;

DROP FUNCTION IF EXISTS public.delete_course_comment(text, bigint);

CREATE OR REPLACE FUNCTION delete_course_comment(pass_code text, p_id bigint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  DELETE FROM public.course_comments WHERE id = p_id;
  RETURN true;
END; $$;

-- L. SAVE SITE CONTENT (CMS)
DROP FUNCTION IF EXISTS public.save_site_content(text, text, jsonb);

CREATE OR REPLACE FUNCTION save_site_content(pass_code text, p_key text, p_content jsonb)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE auth_ok boolean;
BEGIN
  SELECT (get_admin_auth(pass_code)) INTO auth_ok;
  IF NOT auth_ok THEN RETURN false; END IF;
  INSERT INTO public.site_content (key, content, updated_at)
  VALUES (p_key, p_content, now())
  ON CONFLICT (key) DO UPDATE SET content = p_content, updated_at = now();
  RETURN true;
END; $$;

-- M. GRANTS FOR ANON ACCESS
GRANT EXECUTE ON FUNCTION get_admin_auth(text) TO anon;
GRANT EXECUTE ON FUNCTION change_admin_password(text, text) TO anon;
GRANT EXECUTE ON FUNCTION get_teachers_admin(text) TO anon;
GRANT EXECUTE ON FUNCTION delete_teacher(text, bigint) TO anon;
GRANT EXECUTE ON FUNCTION get_teacher_bookings(text) TO anon;
GRANT EXECUTE ON FUNCTION update_booking_status(text, bigint, text, text) TO anon;
GRANT EXECUTE ON FUNCTION get_teacher_reviews_admin(text) TO anon;
GRANT EXECUTE ON FUNCTION approve_teacher_review(text, bigint) TO anon;
GRANT EXECUTE ON FUNCTION delete_teacher_review(text, bigint) TO anon;
GRANT EXECUTE ON FUNCTION get_teacher_applications(text, text) TO anon;
GRANT EXECUTE ON FUNCTION approve_teacher_application(text, bigint, text, text, integer, text) TO anon;
GRANT EXECUTE ON FUNCTION reject_teacher_application(text, bigint, text) TO anon;
GRANT EXECUTE ON FUNCTION delete_teacher_application(text, bigint) TO anon;
GRANT EXECUTE ON FUNCTION delete_institution_review(text, bigint) TO anon;
GRANT EXECUTE ON FUNCTION delete_course_comment(text, bigint) TO anon;
GRANT EXECUTE ON FUNCTION save_site_content(text, text, jsonb) TO anon;

-- ══════════════════════════════════════════════════════════════════════
-- SETUP COMPLETED SUCCESSFULLY!
-- ══════════════════════════════════════════════════════════════════════
